// Package cmakecfg synthesizes a drop-in replacement for the cmake-config
// bundle that install(EXPORT) would have produced for the package. The bundle
// lets downstream CMake projects do `find_package(<Pkg> CONFIG REQUIRED)` and
// see the same imported targets they would have seen against an upstream
// `make install` of the project.
//
// Bundle layout (mirrors what cmake's cmExportCMakeConfigGenerator produces;
// see Source/cmExportCMakeConfigGenerator.cxx in the analysis doc):
//
//	<Pkg>Config.cmake          (find_package entry point)
//	<Pkg>Targets.cmake         (imported-target declarations)
//	<Pkg>Targets-release.cmake (per-config IMPORTED_LOCATION)
//
// Synthesis intentionally drops the multi-inclusion-protection block from
// upstream's emitter; consumers that re-include in the same scope can opt in
// later. The EXISTS-check loop at the bottom of <Pkg>Targets.cmake is
// preserved because docs/cmake_analysis.md documents that loop as the reason the
// shadow-prefix tree just needs to satisfy access(R_OK) — not actually carry
// content.
package cmakecfg

import (
	"bytes"
	"fmt"
	"path"
	"text/template"

	"github.com/sstriker/cmake-to-bazel/converter/internal/ir"
)

// Bundle is the in-memory representation of one cmake-config directory.
// Files maps relative path -> contents.
type Bundle struct {
	Files map[string][]byte
}

// Options affect bundle synthesis. Defaults are sensible for hello-world-shape
// packages.
type Options struct {
	// Namespace is the prefix added to imported targets. Defaults to
	// "<Package>::". Set explicitly when the upstream uses a different
	// convention (e.g. "Foo::" when project is "foo").
	Namespace string

	// Configs lists the per-config bundle files to emit. Defaults to
	// ["Release"].
	Configs []string
}

// Emit produces a Bundle for pkg. Only kinds that map onto IMPORTED targets
// are exposed (libraries: STATIC/SHARED/MODULE/INTERFACE). Executables and
// genrules are filtered — find_package consumers don't import binaries.
func Emit(pkg *ir.Package, opts Options) (*Bundle, error) {
	if pkg.Name == "" {
		return nil, fmt.Errorf("cmakecfg.Emit: package has empty Name")
	}
	if opts.Namespace == "" {
		opts.Namespace = pkg.Name + "::"
	}
	if len(opts.Configs) == 0 {
		opts.Configs = []string{"Release"}
	}

	libs := filterImportable(pkg.Targets)
	if len(libs) == 0 {
		return nil, fmt.Errorf("cmakecfg.Emit: no importable library targets")
	}

	b := &Bundle{Files: map[string][]byte{}}

	cfg, err := renderConfig(pkg.Name)
	if err != nil {
		return nil, err
	}
	b.Files[pkg.Name+"Config.cmake"] = cfg

	tgts, err := renderTargets(pkg.Name, opts.Namespace, libs)
	if err != nil {
		return nil, err
	}
	b.Files[pkg.Name+"Targets.cmake"] = tgts

	for _, conf := range opts.Configs {
		name := pkg.Name + "Targets-" + lowercase(conf) + ".cmake"
		body, err := renderTargetsConfig(opts.Namespace, libs, conf)
		if err != nil {
			return nil, err
		}
		b.Files[name] = body
	}
	return b, nil
}

func filterImportable(ts []ir.Target) []ir.Target {
	var out []ir.Target
	for _, t := range ts {
		switch t.Kind {
		case ir.KindCCLibrary, ir.KindCCInterface, ir.KindCCImport:
			out = append(out, t)
		}
	}
	return out
}

// importedKind picks the CMake STATIC|SHARED|INTERFACE keyword for a target.
func importedKind(t ir.Target) string {
	if t.Kind == ir.KindCCInterface {
		return "INTERFACE"
	}
	if t.Linkstatic {
		return "STATIC"
	}
	return "SHARED"
}

func lowercase(s string) string {
	out := make([]byte, len(s))
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c >= 'A' && c <= 'Z' {
			c += 'a' - 'A'
		}
		out[i] = c
	}
	return string(out)
}

func uppercase(s string) string {
	out := make([]byte, len(s))
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c >= 'a' && c <= 'z' {
			c -= 'a' - 'A'
		}
		out[i] = c
	}
	return string(out)
}

const configTemplateSrc = `# Generated by convert-element. DO NOT EDIT.
include("${CMAKE_CURRENT_LIST_DIR}/{{.Pkg}}Targets.cmake")
`

const targetsTemplateSrc = `# Generated by convert-element. DO NOT EDIT.
# Computes _IMPORT_PREFIX as the parent of lib/cmake/<Pkg>/.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

{{range .Targets -}}
add_library({{$.NS}}{{.Name}} {{importedKind .}} IMPORTED)
{{- if eq (importedKind .) "INTERFACE"}}
{{- else}}
{{end -}}
{{- if .Includes}}
set_target_properties({{$.NS}}{{.Name}} PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)
{{end}}
{{end -}}

# Per-config target details.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/{{.Pkg}}Targets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

set(_IMPORT_PREFIX)

# Verify referenced artifacts exist (access(R_OK) — content not read).
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "Imported target \"${_cmake_target}\" references missing file \"${_cmake_file}\"")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)
`

const targetsConfigTemplateSrc = `# Generated by convert-element. DO NOT EDIT.
# Per-config import file for "{{.Config}}".

{{range .Targets -}}
{{- if .ArtifactName -}}
set_property(TARGET {{$.NS}}{{.Name}} APPEND PROPERTY IMPORTED_CONFIGURATIONS {{$.UpperConfig}})
set_target_properties({{$.NS}}{{.Name}} PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_{{$.UpperConfig}} "{{.LinkLanguage}}"
  IMPORTED_LOCATION_{{$.UpperConfig}} "${_IMPORT_PREFIX}/{{installPath .}}"
)

list(APPEND _cmake_import_check_targets {{$.NS}}{{.Name}})
list(APPEND _cmake_import_check_files_for_{{$.NS}}{{.Name}} "${_IMPORT_PREFIX}/{{installPath .}}")
{{end}}
{{end -}}`

func renderConfig(pkg string) ([]byte, error) {
	t := template.Must(template.New("config").Parse(configTemplateSrc))
	var b bytes.Buffer
	if err := t.Execute(&b, map[string]string{"Pkg": pkg}); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

func renderTargets(pkg, ns string, targets []ir.Target) ([]byte, error) {
	funcs := template.FuncMap{
		"importedKind": importedKind,
	}
	t := template.Must(template.New("tgts").Funcs(funcs).Parse(targetsTemplateSrc))
	var b bytes.Buffer
	if err := t.Execute(&b, map[string]any{
		"Pkg":     pkg,
		"NS":      ns,
		"Targets": targets,
	}); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

func renderTargetsConfig(ns string, targets []ir.Target, conf string) ([]byte, error) {
	funcs := template.FuncMap{
		"installPath": installPath,
	}
	t := template.Must(template.New("tgtsCfg").Funcs(funcs).Parse(targetsConfigTemplateSrc))
	var b bytes.Buffer
	if err := t.Execute(&b, map[string]any{
		"Config":      conf,
		"UpperConfig": uppercase(conf),
		"NS":          ns,
		"Targets":     targets,
	}); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// installPath joins InstallDest and ArtifactName, defaulting destination to
// "lib" if unset (matches CMake's GNUInstallDirs default for libraries).
func installPath(t ir.Target) string {
	dest := t.InstallDest
	if dest == "" {
		dest = "lib"
	}
	return path.Join(dest, t.ArtifactName)
}
