// Package cmaketoolchain renders a toolchain.Model as a CMake
// toolchain file (`toolchain.cmake`). Setting it via
// -DCMAKE_TOOLCHAIN_FILE pre-populates every cache variable cmake
// would otherwise have to probe — compiler identification, ABI
// introspection, builtin search paths, binutils tool paths.
//
// Rationale: per-element cmake invocations spend a measurable
// fraction of their wall-clock time re-running the same compiler
// probe that derive-toolchain already executed once. With this
// file in hand, the orchestrator passes -DCMAKE_TOOLCHAIN_FILE on
// every conversion and cmake skips the probe entirely.
//
// The output is not a full Bazel-side artifact — it's a cmake
// integration aid. derive-toolchain writes both BUILD.bazel
// (downstream Bazel consumers) and toolchain.cmake (per-conversion
// probe avoidance).
package cmaketoolchain

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/sstriker/cmake-to-bazel/converter/internal/toolchain"
)

// Emit renders a Model as the bytes of a CMake toolchain file. The
// caller writes them to disk wherever convenient (typically the
// derive-toolchain output dir alongside BUILD.bazel).
//
// The model must have at least one Language with a non-empty
// CompilerPath; otherwise no useful skip is possible and we
// return an error.
func Emit(m *toolchain.Model) ([]byte, error) {
	if m == nil {
		return nil, fmt.Errorf("cmaketoolchain.Emit: nil model")
	}
	hasCompiler := false
	for _, l := range m.Languages {
		if l.CompilerPath != "" {
			hasCompiler = true
			break
		}
	}
	if !hasCompiler {
		return nil, fmt.Errorf("cmaketoolchain.Emit: model has no compiler paths to skip probing")
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by derive-toolchain. DO NOT EDIT.\n")
	buf.WriteString("#\n")
	buf.WriteString("# Pre-populates cmake's compiler-probe cache so per-conversion\n")
	buf.WriteString("# cmake invocations skip the compiler-detection / ABI / builtin-\n")
	buf.WriteString("# include probing they'd otherwise re-do every time. Pass to cmake\n")
	buf.WriteString("# via -DCMAKE_TOOLCHAIN_FILE=<path-to-this-file>.\n")
	buf.WriteString("\n")

	// Optimization: skip try_compile's link step. CMake's
	// try_compile defaults to building an executable (and thus
	// invokes the linker); STATIC_LIBRARY skips link, which is
	// safe when CMAKE_*_COMPILER_WORKS is already set.
	buf.WriteString("set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY CACHE STRING \"\" FORCE)\n")
	buf.WriteString("\n")

	// Platform identification. Some cmake modules check these
	// before toolchain probing; setting them keeps platform-
	// specific shims consistent.
	if m.HostPlatform.OS != "" {
		fmt.Fprintf(&buf, "set(CMAKE_HOST_SYSTEM_NAME      %q CACHE STRING \"\" FORCE)\n", m.HostPlatform.OS)
	}
	if m.HostPlatform.CPU != "" {
		fmt.Fprintf(&buf, "set(CMAKE_HOST_SYSTEM_PROCESSOR %q CACHE STRING \"\" FORCE)\n", m.HostPlatform.CPU)
	}
	if m.TargetPlatform.OS != "" {
		fmt.Fprintf(&buf, "set(CMAKE_SYSTEM_NAME           %q CACHE STRING \"\" FORCE)\n", m.TargetPlatform.OS)
	}
	if m.TargetPlatform.CPU != "" {
		fmt.Fprintf(&buf, "set(CMAKE_SYSTEM_PROCESSOR      %q CACHE STRING \"\" FORCE)\n", m.TargetPlatform.CPU)
	}
	buf.WriteString("\n")

	// Per-language compiler identification. Order languages by
	// name for deterministic output. C first by convention so
	// CMake's enable_language(C) doesn't see CXX values first.
	for _, lang := range orderedLanguages(m) {
		l := m.Languages[lang]
		emitLanguage(&buf, lang, l)
		buf.WriteString("\n")
	}

	// Binutils tool paths. cmake usually looks these up via
	// CMakeFindBinUtils.cmake (gcc) or platform-specific
	// equivalents; pre-setting eliminates that path-walk.
	emitToolIfSet(&buf, "CMAKE_AR", m.Tools.AR)
	emitToolIfSet(&buf, "CMAKE_RANLIB", m.Tools.Ranlib)
	emitToolIfSet(&buf, "CMAKE_STRIP", m.Tools.Strip)
	emitToolIfSet(&buf, "CMAKE_NM", m.Tools.NM)
	emitToolIfSet(&buf, "CMAKE_OBJCOPY", m.Tools.Objcopy)
	emitToolIfSet(&buf, "CMAKE_OBJDUMP", m.Tools.Objdump)
	emitToolIfSet(&buf, "CMAKE_LINKER", m.Tools.Linker)

	return buf.Bytes(), nil
}

func emitLanguage(buf *bytes.Buffer, lang string, l toolchain.Language) {
	fmt.Fprintf(buf, "# %s language\n", lang)
	if l.CompilerPath != "" {
		fmt.Fprintf(buf, "set(CMAKE_%s_COMPILER %q CACHE FILEPATH \"\" FORCE)\n",
			lang, l.CompilerPath)
	}
	if l.CompilerID != "" {
		fmt.Fprintf(buf, "set(CMAKE_%s_COMPILER_ID %q CACHE STRING \"\" FORCE)\n",
			lang, l.CompilerID)
	}
	if l.Version != "" {
		fmt.Fprintf(buf, "set(CMAKE_%s_COMPILER_VERSION %q CACHE STRING \"\" FORCE)\n",
			lang, l.Version)
	}
	if l.Target != "" {
		fmt.Fprintf(buf, "set(CMAKE_%s_COMPILER_TARGET %q CACHE STRING \"\" FORCE)\n",
			lang, l.Target)
	}

	// "Compiler works" + "ABI compiled" sentinels: setting both
	// makes cmake skip the try_compile probe that detects the
	// compiler driver works at all and the ABI introspection
	// (sizeof pointer / endianness / etc.). The ABI values that
	// would normally be derived from the probe are reasonable
	// defaults for any modern Unix-like target; downstream rules
	// rarely depend on exact ABI bits.
	fmt.Fprintf(buf, "set(CMAKE_%s_COMPILER_WORKS TRUE CACHE INTERNAL \"\")\n", lang)
	fmt.Fprintf(buf, "set(CMAKE_%s_ABI_COMPILED TRUE CACHE INTERNAL \"\")\n", lang)
	fmt.Fprintf(buf, "set(CMAKE_%s_COMPILER_LOADED 1 CACHE INTERNAL \"\")\n", lang)

	// Builtin include / link directories — cmake uses these to
	// filter out -I/-L flags consumers redundantly add.
	emitListIfSet(buf, fmt.Sprintf("CMAKE_%s_IMPLICIT_INCLUDE_DIRECTORIES", lang), l.BuiltinIncludeDirs)
	emitListIfSet(buf, fmt.Sprintf("CMAKE_%s_IMPLICIT_LINK_DIRECTORIES", lang), l.BuiltinLinkDirs)

	// Init flags: the *_INIT variants seed defaults consumers
	// can append to. We don't FORCE these because projects often
	// merge their own flags on top.
	if len(l.BaseFlags) > 0 {
		fmt.Fprintf(buf, "set(CMAKE_%s_FLAGS_INIT %q)\n", lang, strings.Join(l.BaseFlags, " "))
	}
}

func emitToolIfSet(buf *bytes.Buffer, name, path string) {
	if path == "" {
		return
	}
	fmt.Fprintf(buf, "set(%s %q CACHE FILEPATH \"\" FORCE)\n", name, path)
}

func emitListIfSet(buf *bytes.Buffer, name string, items []string) {
	if len(items) == 0 {
		return
	}
	fmt.Fprintf(buf, "set(%s %q CACHE INTERNAL \"\")\n", name, strings.Join(items, ";"))
}

// orderedLanguages returns m.Languages keys in C-then-CXX-then-rest
// order. Deterministic output helps debugging + diffing across
// runs.
func orderedLanguages(m *toolchain.Model) []string {
	priority := []string{"C", "CXX"}
	out := []string{}
	seen := map[string]bool{}
	for _, p := range priority {
		if _, ok := m.Languages[p]; ok {
			out = append(out, p)
			seen[p] = true
		}
	}
	rest := []string{}
	for k := range m.Languages {
		if !seen[k] {
			rest = append(rest, k)
		}
	}
	// Stable ordering for the rest.
	for i := 0; i < len(rest); i++ {
		for j := i + 1; j < len(rest); j++ {
			if rest[j] < rest[i] {
				rest[i], rest[j] = rest[j], rest[i]
			}
		}
	}
	return append(out, rest...)
}
