package cmaketoolchain

import (
	"strings"
	"testing"

	"github.com/sstriker/cmake-to-bazel/converter/internal/fileapi"
	"github.com/sstriker/cmake-to-bazel/converter/internal/toolchain"
)

func TestEmit_StructuralAssertions(t *testing.T) {
	r, err := fileapi.Load("../../../testdata/fileapi/hello-world")
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	m, err := toolchain.FromReply(r)
	if err != nil {
		t.Fatalf("FromReply: %v", err)
	}
	body, err := Emit(m)
	if err != nil {
		t.Fatalf("Emit: %v", err)
	}
	out := string(body)

	for _, want := range []string{
		// header / framing
		`Generated by derive-toolchain`,
		// per-language compiler identification
		`set(CMAKE_C_COMPILER`,
		`set(CMAKE_C_COMPILER_ID "GNU"`,
		`set(CMAKE_C_COMPILER_WORKS TRUE`,
		// builtin includes / link dirs
		`CMAKE_C_IMPLICIT_INCLUDE_DIRECTORIES`,
		`CMAKE_C_IMPLICIT_LINK_DIRECTORIES`,
		// binutils
		`set(CMAKE_AR`,
	} {
		if !strings.Contains(out, want) {
			t.Errorf("output missing %q\n%s", want, out)
		}
	}
}

func TestEmit_NilModelRejected(t *testing.T) {
	if _, err := Emit(nil); err == nil {
		t.Error("Emit(nil) should error")
	}
}

func TestEmit_NoCompilerPathRejected(t *testing.T) {
	m := &toolchain.Model{
		Languages: map[string]toolchain.Language{
			"C": {CompilerID: "GNU"}, // no path
		},
	}
	if _, err := Emit(m); err == nil {
		t.Error("Emit on model with no compiler paths should error")
	}
}

func TestEmit_EmitsCXXAfterC(t *testing.T) {
	m := &toolchain.Model{
		Languages: map[string]toolchain.Language{
			"CXX": {CompilerPath: "/usr/bin/g++", CompilerID: "GNU"},
			"C":   {CompilerPath: "/usr/bin/gcc", CompilerID: "GNU"},
		},
	}
	body, err := Emit(m)
	if err != nil {
		t.Fatalf("Emit: %v", err)
	}
	out := string(body)
	cIdx := strings.Index(out, "# C language")
	cxxIdx := strings.Index(out, "# CXX language")
	if cIdx == -1 || cxxIdx == -1 {
		t.Fatalf("missing language section markers (cIdx=%d, cxxIdx=%d)", cIdx, cxxIdx)
	}
	if cIdx > cxxIdx {
		t.Errorf("C should come before CXX; got C@%d CXX@%d", cIdx, cxxIdx)
	}
}

func TestEmit_OmitsEmptyOptionalFields(t *testing.T) {
	m := &toolchain.Model{
		Languages: map[string]toolchain.Language{
			"C": {
				CompilerPath: "/usr/bin/gcc",
				// CompilerID, Version, Target left empty.
			},
		},
		// Tools all empty.
	}
	body, err := Emit(m)
	if err != nil {
		t.Fatalf("Emit: %v", err)
	}
	out := string(body)
	for _, dontwant := range []string{
		`COMPILER_ID ""`,
		`COMPILER_VERSION ""`,
		`COMPILER_TARGET ""`,
		`set(CMAKE_AR ""`,
	} {
		if strings.Contains(out, dontwant) {
			t.Errorf("output contained empty optional field %q\n%s", dontwant, out)
		}
	}
}
