// Package cmaketoolchain renders a toolchain.Model as a CMake
// toolchain file (`toolchain.cmake`). Setting it via
// -DCMAKE_TOOLCHAIN_FILE pre-populates every cache variable cmake
// would otherwise have to probe — compiler identification, ABI
// introspection, builtin search paths, binutils tool paths.
//
// Rationale: per-element cmake invocations spend a measurable
// fraction of their wall-clock time re-running the same compiler
// probe that derive-toolchain already executed once. With this
// file in hand, the orchestrator passes -DCMAKE_TOOLCHAIN_FILE on
// every conversion and cmake skips the probe entirely.
//
// The output is not a full Bazel-side artifact — it's a cmake
// integration aid. derive-toolchain writes both BUILD.bazel
// (downstream Bazel consumers) and toolchain.cmake (per-conversion
// probe avoidance).
package cmaketoolchain

import (
	"bytes"
	"fmt"
	"runtime"
	"strings"

	"github.com/sstriker/cmake-to-bazel/converter/internal/toolchain"
)

// Emit renders a Model as the bytes of a CMake toolchain file. The
// caller writes them to disk wherever convenient (typically the
// derive-toolchain output dir alongside BUILD.bazel).
//
// The model must have at least one Language with a non-empty
// CompilerPath; otherwise no useful skip is possible and we
// return an error.
func Emit(m *toolchain.Model) ([]byte, error) {
	if m == nil {
		return nil, fmt.Errorf("cmaketoolchain.Emit: nil model")
	}
	hasCompiler := false
	for _, l := range m.Languages {
		if l.CompilerPath != "" {
			hasCompiler = true
			break
		}
	}
	if !hasCompiler {
		return nil, fmt.Errorf("cmaketoolchain.Emit: model has no compiler paths to skip probing")
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by derive-toolchain. DO NOT EDIT.\n")
	buf.WriteString("#\n")
	buf.WriteString("# Pre-populates cmake's compiler-probe cache so per-conversion\n")
	buf.WriteString("# cmake invocations skip the compiler-detection / ABI / builtin-\n")
	buf.WriteString("# include probing they'd otherwise re-do every time. Pass to cmake\n")
	buf.WriteString("# via -DCMAKE_TOOLCHAIN_FILE=<path-to-this-file>.\n")
	buf.WriteString("\n")

	// We deliberately do NOT set CMAKE_TRY_COMPILE_TARGET_TYPE
	// STATIC_LIBRARY here. cmake's CMakeDetermineCompilerABI
	// module uses try_compile internally to build a probe binary
	// it then reads via file(READ_ELF) to derive
	// CMAKE_EXECUTABLE_FORMAT (ELF/PE/Mach-O/...). Forcing the
	// target type to STATIC_LIBRARY makes the probe emit an .a
	// instead of an executable, READ_ELF returns "Unknown", and
	// the Ninja generator then fails install(TARGETS …) with
	// "requires changing an RPATH from the build tree, but this
	// is not supported … unless on an ELF-based or XCOFF-based
	// platform". Skipping linker time on user-code try_compile
	// isn't worth breaking install rules.

	// Platform identification. Some cmake modules check these
	// before toolchain probing; setting them keeps platform-
	// specific shims consistent.
	if m.HostPlatform.OS != "" {
		fmt.Fprintf(&buf, "set(CMAKE_HOST_SYSTEM_NAME      %q CACHE STRING \"\" FORCE)\n", m.HostPlatform.OS)
	}
	if m.HostPlatform.CPU != "" {
		fmt.Fprintf(&buf, "set(CMAKE_HOST_SYSTEM_PROCESSOR %q CACHE STRING \"\" FORCE)\n", m.HostPlatform.CPU)
	}
	if m.TargetPlatform.OS != "" {
		fmt.Fprintf(&buf, "set(CMAKE_SYSTEM_NAME           %q CACHE STRING \"\" FORCE)\n", m.TargetPlatform.OS)
	}
	if m.TargetPlatform.CPU != "" {
		fmt.Fprintf(&buf, "set(CMAKE_SYSTEM_PROCESSOR      %q CACHE STRING \"\" FORCE)\n", m.TargetPlatform.CPU)
	}

	// CMAKE_EXECUTABLE_FORMAT is normally set by
	// CMakeDetermineCompilerId.cmake's CMAKE_DETERMINE_COMPILER_ID_CHECK
	// — it reads the magic bytes of the compiler-ID-test output. But
	// CHECK only runs when CMAKE_<LANG>_COMPILER_ID is unset, and we
	// pre-cache that to skip vendor detection. The result: cmake
	// caches CMAKE_EXECUTABLE_FORMAT="Unknown", which then makes the
	// Ninja generator's install(TARGETS …) reject the target with
	// "requires changing an RPATH from the build tree, but this is
	// not supported … unless on an ELF-based or XCOFF-based platform".
	// Pre-setting based on target OS sidesteps the gap.
	targetOS := m.TargetPlatform.OS
	if targetOS == "" {
		// Probe didn't surface CMAKE_SYSTEM_NAME (it lives in
		// CMakeSystem.cmake, not CMakeCache.txt, and the current
		// extractor only reads the cache). Fall back to runtime.GOOS:
		// derive-toolchain always probes the local host, so the
		// runtime is the correct target absent explicit cross-compile.
		targetOS = goosToCmakeSystem(runtime.GOOS)
	}
	if exeFmt := executableFormat(targetOS); exeFmt != "" {
		fmt.Fprintf(&buf, "set(CMAKE_EXECUTABLE_FORMAT     %q CACHE INTERNAL \"Executable file format\")\n", exeFmt)
	}
	buf.WriteString("\n")

	// Per-language compiler identification. Order languages by
	// name for deterministic output. C first by convention so
	// CMake's enable_language(C) doesn't see CXX values first.
	for _, lang := range orderedLanguages(m) {
		l := m.Languages[lang]
		emitLanguage(&buf, lang, l)
		buf.WriteString("\n")
	}

	// Binutils tool paths. cmake usually looks these up via
	// CMakeFindBinUtils.cmake (gcc) or platform-specific
	// equivalents; pre-setting eliminates that path-walk.
	emitToolIfSet(&buf, "CMAKE_AR", m.Tools.AR)
	emitToolIfSet(&buf, "CMAKE_RANLIB", m.Tools.Ranlib)
	emitToolIfSet(&buf, "CMAKE_STRIP", m.Tools.Strip)
	emitToolIfSet(&buf, "CMAKE_NM", m.Tools.NM)
	emitToolIfSet(&buf, "CMAKE_OBJCOPY", m.Tools.Objcopy)
	emitToolIfSet(&buf, "CMAKE_OBJDUMP", m.Tools.Objdump)
	emitToolIfSet(&buf, "CMAKE_LINKER", m.Tools.Linker)

	return buf.Bytes(), nil
}

func emitLanguage(buf *bytes.Buffer, lang string, l toolchain.Language) {
	fmt.Fprintf(buf, "# %s language\n", lang)
	if l.CompilerPath != "" {
		fmt.Fprintf(buf, "set(CMAKE_%s_COMPILER %q CACHE FILEPATH \"\" FORCE)\n",
			lang, l.CompilerPath)
	}
	if l.CompilerID != "" {
		fmt.Fprintf(buf, "set(CMAKE_%s_COMPILER_ID %q CACHE STRING \"\" FORCE)\n",
			lang, l.CompilerID)
	}
	if l.Version != "" {
		fmt.Fprintf(buf, "set(CMAKE_%s_COMPILER_VERSION %q CACHE STRING \"\" FORCE)\n",
			lang, l.Version)
	}
	if l.Target != "" {
		fmt.Fprintf(buf, "set(CMAKE_%s_COMPILER_TARGET %q CACHE STRING \"\" FORCE)\n",
			lang, l.Target)
	}

	// CMAKE_<LANG>_COMPILER_WORKS skips the try_compile probe that
	// builds CMakeCCompilerId.c just to confirm the driver runs.
	// That's the slowest part of compiler detection.
	//
	// We deliberately do NOT set CMAKE_<LANG>_ABI_COMPILED — that
	// would skip CMakeDetermineCompilerABI.cmake, which derives
	// CMAKE_EXECUTABLE_FORMAT (ELF/PE/XCOFF), CMAKE_<LANG>_COMPILER_ABI,
	// byte order, sizeof(void*), and CMAKE_LIBRARY_ARCHITECTURE.
	// Downstream cmake code (notably the Ninja generator's RPATH
	// install logic) hard-fails when EXECUTABLE_FORMAT is unset.
	// Letting the ABI probe run costs ~0.1s but keeps every
	// install(TARGETS …) consumer working.
	fmt.Fprintf(buf, "set(CMAKE_%s_COMPILER_WORKS TRUE CACHE INTERNAL \"\")\n", lang)
	fmt.Fprintf(buf, "set(CMAKE_%s_COMPILER_LOADED 1 CACHE INTERNAL \"\")\n", lang)

	// Pre-set STANDARD/EXTENSIONS_COMPUTED_DEFAULT so cmake 3.31+'s
	// __compiler_check_default_language_standard macro
	// (Modules/Compiler/CMakeCommonCompilerMacros.cmake:42) doesn't
	// abort with "CMAKE_<LANG>_STANDARD_COMPUTED_DEFAULT and
	// CMAKE_<LANG>_EXTENSIONS_COMPUTED_DEFAULT should be set for
	// <id> (<path>) version <ver>". Pre-cached compilers bypass the
	// per-compiler module that would otherwise fill these in.
	if std := defaultLanguageStandard(lang, l.CompilerID, l.Version); std != "" {
		fmt.Fprintf(buf, "set(CMAKE_%s_STANDARD_COMPUTED_DEFAULT %q)\n", lang, std)
		fmt.Fprintf(buf, "set(CMAKE_%s_EXTENSIONS_COMPUTED_DEFAULT ON)\n", lang)
	}

	// Builtin include / link directories — cmake uses these to
	// filter out -I/-L flags consumers redundantly add.
	emitListIfSet(buf, fmt.Sprintf("CMAKE_%s_IMPLICIT_INCLUDE_DIRECTORIES", lang), l.BuiltinIncludeDirs)
	emitListIfSet(buf, fmt.Sprintf("CMAKE_%s_IMPLICIT_LINK_DIRECTORIES", lang), l.BuiltinLinkDirs)

	// Init flags: the *_INIT variants seed defaults consumers
	// can append to. We don't FORCE these because projects often
	// merge their own flags on top.
	if len(l.BaseFlags) > 0 {
		fmt.Fprintf(buf, "set(CMAKE_%s_FLAGS_INIT %q)\n", lang, strings.Join(l.BaseFlags, " "))
	}
}

func emitToolIfSet(buf *bytes.Buffer, name, path string) {
	if path == "" {
		return
	}
	fmt.Fprintf(buf, "set(%s %q CACHE FILEPATH \"\" FORCE)\n", name, path)
}

func emitListIfSet(buf *bytes.Buffer, name string, items []string) {
	if len(items) == 0 {
		return
	}
	fmt.Fprintf(buf, "set(%s %q CACHE INTERNAL \"\")\n", name, strings.Join(items, ";"))
}

// goosToCmakeSystem maps a Go runtime.GOOS string to the cmake
// CMAKE_SYSTEM_NAME spelling. Used as a fallback when probe data
// doesn't surface CMAKE_SYSTEM_NAME directly.
func goosToCmakeSystem(goos string) string {
	switch goos {
	case "linux":
		return "Linux"
	case "darwin":
		return "Darwin"
	case "windows":
		return "Windows"
	case "freebsd":
		return "FreeBSD"
	case "openbsd":
		return "OpenBSD"
	case "netbsd":
		return "NetBSD"
	case "android":
		return "Android"
	case "solaris", "illumos":
		return "SunOS"
	case "aix":
		return "AIX"
	}
	return ""
}

// executableFormat returns the binary container format cmake uses
// for the given target OS. Mirrors what
// CMakeDetermineCompilerId.cmake's magic-byte sniffer would
// otherwise derive at probe time.
func executableFormat(os string) string {
	switch os {
	case "Linux", "FreeBSD", "OpenBSD", "NetBSD", "DragonFly", "GNU", "Android", "SunOS", "Solaris":
		return "ELF"
	case "Darwin", "iOS", "tvOS", "watchOS":
		return "MACHO"
	case "AIX":
		return "XCOFF"
	}
	return ""
}

// defaultLanguageStandard returns the value cmake's per-compiler
// modules pre-set CMAKE_<lang>_STANDARD_COMPUTED_DEFAULT to for the
// given compiler ID + version. Mirrors the version→standard tables
// in Modules/Compiler/<ID>-<lang>.cmake so derive-toolchain's
// emitted toolchain.cmake plays nicely with cmake 3.31+'s strict
// __compiler_check_default_language_standard macro.
//
// Returns "" if we don't have a table for this (compiler, language)
// pair; the caller skips emitting the COMPUTED_DEFAULT lines and
// cmake's normal compiler-detection path runs (the COMPILER cache
// var is still pre-populated, so it's just the per-language module
// that re-runs — minor cost vs. the wholesale probe).
func defaultLanguageStandard(lang, compilerID, version string) string {
	major, minor := parseCompilerVersion(version)
	switch compilerID {
	case "GNU":
		// Tables match v3.31's GNU-C.cmake / GNU-CXX.cmake invocations:
		//   __compiler_check_default_language_standard(C   3.4 90 5.0 11 8.1 17)
		//   __compiler_check_default_language_standard(CXX 3.4 98 6.0 14 11.1 17)
		switch lang {
		case "C":
			switch {
			case atLeast(major, minor, 8, 1):
				return "17"
			case atLeast(major, minor, 5, 0):
				return "11"
			case atLeast(major, minor, 3, 4):
				return "90"
			}
		case "CXX":
			switch {
			case atLeast(major, minor, 11, 1):
				return "17"
			case atLeast(major, minor, 6, 0):
				return "14"
			case atLeast(major, minor, 3, 4):
				return "98"
			}
		}
	case "Clang", "AppleClang":
		// Modules/Compiler/Clang-{C,CXX}.cmake use the same shape:
		//   __compiler_check_default_language_standard(C   2.1 90 3.4 11 6.0 17)
		//   __compiler_check_default_language_standard(CXX 2.1 98 3.6 14 6.0 17)
		switch lang {
		case "C":
			switch {
			case atLeast(major, minor, 6, 0):
				return "17"
			case atLeast(major, minor, 3, 4):
				return "11"
			case atLeast(major, minor, 2, 1):
				return "90"
			}
		case "CXX":
			switch {
			case atLeast(major, minor, 6, 0):
				return "17"
			case atLeast(major, minor, 3, 6):
				return "14"
			case atLeast(major, minor, 2, 1):
				return "98"
			}
		}
	}
	return ""
}

func parseCompilerVersion(v string) (major, minor int) {
	parts := strings.SplitN(v, ".", 3)
	if len(parts) >= 1 {
		fmt.Sscanf(parts[0], "%d", &major)
	}
	if len(parts) >= 2 {
		fmt.Sscanf(parts[1], "%d", &minor)
	}
	return
}

func atLeast(major, minor, wantMajor, wantMinor int) bool {
	if major != wantMajor {
		return major > wantMajor
	}
	return minor >= wantMinor
}

// orderedLanguages returns m.Languages keys in C-then-CXX-then-rest
// order. Deterministic output helps debugging + diffing across
// runs.
func orderedLanguages(m *toolchain.Model) []string {
	priority := []string{"C", "CXX"}
	out := []string{}
	seen := map[string]bool{}
	for _, p := range priority {
		if _, ok := m.Languages[p]; ok {
			out = append(out, p)
			seen[p] = true
		}
	}
	rest := []string{}
	for k := range m.Languages {
		if !seen[k] {
			rest = append(rest, k)
		}
	}
	// Stable ordering for the rest.
	for i := 0; i < len(rest); i++ {
		for j := i + 1; j < len(rest); j++ {
			if rest[j] < rest[i] {
				rest[i], rest[j] = rest[j], rest[i]
			}
		}
	}
	return append(out, rest...)
}
