// Package bazel emits a BUILD.bazel file from the IR.
//
// M1 uses text/template for stable, easy-to-diff output and zero external
// deps. The plan calls for a buildtools-AST spike in week 1; if it's adopted,
// it replaces the template here without changing the Emit signature.
//
// Output is deterministic: every list attribute is sorted before emission.
package bazel

import (
	"bytes"
	"fmt"
	"sort"
	"text/template"

	"github.com/sstriker/cmake-to-bazel/converter/internal/ir"
)

const header = `# Generated by convert-element. DO NOT EDIT.
# Source: %s

`

// Emit returns the contents of a BUILD.bazel file for pkg.
func Emit(pkg *ir.Package) ([]byte, error) {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, header, pkg.SourceRoot)

	for i, t := range pkg.Targets {
		if i > 0 {
			buf.WriteString("\n")
		}
		if err := emitTarget(&buf, t); err != nil {
			return nil, err
		}
	}
	return buf.Bytes(), nil
}

var ruleTmpl = template.Must(template.New("rule").Funcs(template.FuncMap{
	"strList": strList,
}).Parse(`{{.RuleKind}}(
    name = "{{.Name}}",
{{- if .Srcs}}
    srcs = {{strList .Srcs}},
{{- end}}
{{- if .Hdrs}}
    hdrs = {{strList .Hdrs}},
{{- end}}
{{- if .Includes}}
    includes = {{strList .Includes}},
{{- end}}
{{- if .Copts}}
    copts = {{strList .Copts}},
{{- end}}
{{- if .Defines}}
    defines = {{strList .Defines}},
{{- end}}
{{- if .Linkopts}}
    linkopts = {{strList .Linkopts}},
{{- end}}
{{- if .Deps}}
    deps = {{strList .Deps}},
{{- end}}
{{- if .Linkstatic}}
    linkstatic = True,
{{- end}}
{{- if .Alwayslink}}
    alwayslink = True,
{{- end}}
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

// templateView is what we hand to the template. We project ir.Target into it
// so we can sort lists once and so the template doesn't need to know about
// ir.Kind.
type templateView struct {
	RuleKind   string
	Name       string
	Srcs       []string
	Hdrs       []string
	Includes   []string
	Copts      []string
	Defines    []string
	Linkopts   []string
	Deps       []string
	Linkstatic bool
	Alwayslink bool
	Visibility []string
}

func emitTarget(w *bytes.Buffer, t ir.Target) error {
	v := templateView{
		RuleKind:   t.Kind.String(),
		Name:       t.Name,
		Srcs:       sortedCopy(t.Srcs),
		Hdrs:       sortedCopy(t.Hdrs),
		Includes:   sortedCopy(t.Includes),
		Copts:      append([]string(nil), t.Copts...), // preserve order; flag order matters
		Defines:    sortedCopy(t.Defines),
		Linkopts:   append([]string(nil), t.LinkOpts...), // preserve order
		Deps:       sortedCopy(t.Deps),
		Linkstatic: t.Linkstatic,
		Alwayslink: t.Alwayslink,
		Visibility: append([]string(nil), t.Visibility...),
	}
	return ruleTmpl.Execute(w, v)
}

func sortedCopy(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	out := append([]string(nil), in...)
	sort.Strings(out)
	return out
}

// strList renders a Go []string as a Starlark list literal:
//
//	["a", "b"]                       (single-line if total <= 60 chars)
//	[
//	    "a",
//	    "b",
//	]                                 (multi-line otherwise)
func strList(items []string) string {
	if len(items) == 0 {
		return "[]"
	}
	// single-line trial
	var single bytes.Buffer
	single.WriteByte('[')
	for i, s := range items {
		if i > 0 {
			single.WriteString(", ")
		}
		single.WriteByte('"')
		single.WriteString(s)
		single.WriteByte('"')
	}
	single.WriteByte(']')
	if single.Len() <= 60 {
		return single.String()
	}
	// multi-line
	var multi bytes.Buffer
	multi.WriteString("[\n")
	for _, s := range items {
		fmt.Fprintf(&multi, "        %q,\n", s)
	}
	multi.WriteString("    ]")
	return multi.String()
}
