// Package bazel emits a BUILD.bazel file from the IR.
//
// M1 uses text/template for stable, easy-to-diff output and zero external
// deps. The plan calls for a buildtools-AST spike in week 1; if it's adopted,
// it replaces the template here without changing the Emit signature.
//
// Output is deterministic: every list attribute is sorted before emission.
package bazel

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"text/template"
	"time"

	"github.com/sstriker/cmake-to-bazel/converter/internal/ir"
)

// header is intentionally path-free so the emitted BUILD.bazel is
// byte-identical across runs, machines, and per-orchestration tmpdirs.
// The element / codebase the file belongs to is implicit in its
// on-disk location (out/elements/<name>/BUILD.bazel for orchestrator
// runs; whatever --out-build the operator passed for standalone runs).
const header = `# Generated by convert-element. DO NOT EDIT.

`

// ccRuleLoads maps each Kind to its rules_cc load symbol. Bazel 9
// removed cc_library/cc_binary/cc_import from the global namespace;
// every emitted BUILD.bazel using one of these rules must `load()`
// it explicitly. Older Bazels accept the load + load-less form alike.
var ccRuleLoads = map[ir.Kind]string{
	ir.KindCCLibrary:   "cc_library",
	ir.KindCCBinary:    "cc_binary",
	ir.KindCCImport:    "cc_import",
	ir.KindCCInterface: "cc_library",
	ir.KindCCTest:      "cc_test",
}

// emitLoad writes a single `load("@rules_cc//cc:defs.bzl", ...)` line
// covering every cc_* symbol used by pkg's targets. Symbols are sorted
// for byte-stability. Returns nothing if pkg has no cc_* targets.
func emitLoad(buf *bytes.Buffer, pkg *ir.Package) {
	used := map[string]struct{}{}
	for _, t := range pkg.Targets {
		if sym, ok := ccRuleLoads[t.Kind]; ok {
			used[sym] = struct{}{}
		}
	}
	if len(used) == 0 {
		return
	}
	syms := make([]string, 0, len(used))
	for s := range used {
		syms = append(syms, s)
	}
	sort.Strings(syms)
	buf.WriteString(`load("@rules_cc//cc:defs.bzl"`)
	for _, s := range syms {
		fmt.Fprintf(buf, ", %q", s)
	}
	buf.WriteString(")\n\n")
}

// Options tunes the BUILD.bazel emission. Zero-value Options
// preserves the legacy relative-path emission.
type Options struct {
	// SourceKey, when non-empty, prefixes every source path in
	// emitted cc_library/cc_binary/cc_test `srcs = [...]` with
	// "@src_<SourceKey>//:" so project B references the bytes
	// by digest-stable Bazel label rather than by local
	// filesystem path. Used by the FUSE-sources route to keep
	// project B's compile actions BwoB without a project-B-side
	// FUSE mount of its own.
	SourceKey string
}

// Emit returns the contents of a BUILD.bazel file for pkg using
// default Options.
func Emit(pkg *ir.Package) ([]byte, error) {
	return EmitWithOptions(pkg, Options{})
}

// EmitWithOptions is the configurable form of Emit.
func EmitWithOptions(pkg *ir.Package, opts Options) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(header)
	emitLoad(&buf, pkg)

	for i, t := range pkg.Targets {
		if i > 0 {
			buf.WriteString("\n")
		}
		if t.Kind == ir.KindGenrule {
			if err := emitGenrule(&buf, t); err != nil {
				return nil, err
			}
			continue
		}
		if err := emitCCTargetWithOptions(&buf, t, opts); err != nil {
			return nil, err
		}
	}
	return buf.Bytes(), nil
}

var ccRuleTmpl = template.Must(template.New("rule").Funcs(template.FuncMap{
	"strList": strList,
	"strDict": strDict,
}).Parse(`{{.RuleKind}}(
    name = "{{.Name}}",
{{- if .Srcs}}
    srcs = {{strList .Srcs}},
{{- end}}
{{- if .Hdrs}}
    hdrs = {{strList .Hdrs}},
{{- end}}
{{- if .Includes}}
    includes = {{strList .Includes}},
{{- end}}
{{- if .Copts}}
    copts = {{strList .Copts}},
{{- end}}
{{- if .Defines}}
    defines = {{strList .Defines}},
{{- end}}
{{- if .Linkopts}}
    linkopts = {{strList .Linkopts}},
{{- end}}
{{- if .Deps}}
    deps = {{strList .Deps}},
{{- end}}
{{- if .Data}}
    data = {{strList .Data}},
{{- end}}
{{- if .Args}}
    args = {{strList .Args}},
{{- end}}
{{- if .Env}}
    env = {{strDict .Env}},
{{- end}}
{{- if .Timeout}}
    timeout = "{{.Timeout}}",
{{- end}}
{{- if .Linkstatic}}
    linkstatic = True,
{{- end}}
{{- if .Alwayslink}}
    alwayslink = True,
{{- end}}
{{- if .Tags}}
    tags = {{strList .Tags}},
{{- end}}
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

var genruleTmpl = template.Must(template.New("genrule").Funcs(template.FuncMap{
	"strList": strList,
}).Parse(`genrule(
    name = "{{.Name}}",
{{- if .Srcs}}
    srcs = {{strList .Srcs}},
{{- end}}
    outs = {{strList .Outs}},
    cmd = {{.CmdLiteral}},
{{- if .Tags}}
    tags = {{strList .Tags}},
{{- end}}
{{- if .Visibility}}
    visibility = {{strList .Visibility}},
{{- end}}
)
`))

// ccView projects ir.Target into the cc-rule template. List attributes are
// pre-sorted; the emitter doesn't make policy decisions. Test-only fields
// (Args, Env, Timeout, Data) stay zero except when RuleKind == "cc_test".
type ccView struct {
	RuleKind   string
	Name       string
	Srcs       []string
	Hdrs       []string
	Includes   []string
	Copts      []string
	Defines    []string
	Linkopts   []string
	Deps       []string
	Linkstatic bool
	Alwayslink bool
	Tags       []string
	Visibility []string

	// cc_test-only.
	Args    []string
	Env     map[string]string
	Timeout string // pre-formatted Bazel duration ("30s", "5m"), empty = unset
	Data    []string
}

type genruleView struct {
	Name       string
	Srcs       []string
	Outs       []string
	CmdLiteral string // already-quoted Starlark string literal
	Tags       []string
	Visibility []string
}

func emitCCTarget(w *bytes.Buffer, t ir.Target) error {
	return emitCCTargetWithOptions(w, t, Options{})
}

func emitCCTargetWithOptions(w *bytes.Buffer, t ir.Target, opts Options) error {
	v := ccView{
		RuleKind:   t.Kind.String(),
		Name:       t.Name,
		Srcs:       sortedCopy(t.Srcs),
		Hdrs:       sortedCopy(t.Hdrs),
		Includes:   sortedCopy(t.Includes),
		Copts:      append([]string(nil), t.Copts...), // preserve order; flag order matters
		Defines:    sortedCopy(t.Defines),
		Linkopts:   append([]string(nil), t.LinkOpts...), // preserve order
		Deps:       sortedCopy(t.Deps),
		Linkstatic: t.Linkstatic,
		Alwayslink: t.Alwayslink,
		Tags:       sortedCopy(t.Tags),
		Visibility: append([]string(nil), t.Visibility...),
	}
	// cc_binary doesn't accept `hdrs` (Bazel 9 errors out where older
	// versions silently ignored). Fold any header into srcs so the
	// translation unit still sees them, even though that's the
	// rules_cc convention for binaries. cc_test inherits cc_binary's
	// stricture, so apply the same fold there.
	if (t.Kind == ir.KindCCBinary || t.Kind == ir.KindCCTest) && len(v.Hdrs) > 0 {
		v.Srcs = append(append([]string{}, v.Srcs...), v.Hdrs...)
		sort.Strings(v.Srcs)
		v.Hdrs = nil
	}
	// FUSE-sources path: rewrite src + hdr paths to @src_<key>//:
	// labels so project B compiles against digest-referenced
	// inputs rather than relative paths. The `@…//:<path>` form
	// preserves the path exactly (no leading slash) — Bazel's
	// label parser handles it.
	if opts.SourceKey != "" {
		v.Srcs = prefixWithSourceLabel(v.Srcs, opts.SourceKey)
		v.Hdrs = prefixWithSourceLabel(v.Hdrs, opts.SourceKey)
	}
	if t.Kind == ir.KindCCTest {
		v.Args = append([]string(nil), t.TestArgs...) // preserve order; arg order matters
		v.Data = sortedCopy(t.TestData)
		if t.TestTimeout > 0 {
			v.Timeout = formatBazelDuration(t.TestTimeout)
		}
		if len(t.TestEnv) > 0 {
			v.Env = make(map[string]string, len(t.TestEnv))
			for _, kv := range t.TestEnv {
				if i := strings.IndexByte(kv, '='); i >= 0 {
					v.Env[kv[:i]] = kv[i+1:]
				}
			}
		}
	}
	return ccRuleTmpl.Execute(w, v)
}

// prefixWithSourceLabel maps relative source paths to
// @src_<key>//:<path> Bazel labels. Returns a fresh slice so the
// caller's view stays untouched on the legacy (non-fuse) path.
func prefixWithSourceLabel(paths []string, key string) []string {
	if len(paths) == 0 {
		return paths
	}
	out := make([]string, len(paths))
	for i, p := range paths {
		out[i] = "@src_" + key + "//:" + p
	}
	return out
}

// formatBazelDuration renders a Go time.Duration as a Bazel-accepted
// timeout string. Bazel accepts "Ns", "Nm", "Nh"; we round to the
// largest unit that doesn't lose precision.
func formatBazelDuration(d time.Duration) string {
	switch {
	case d%time.Hour == 0:
		return fmt.Sprintf("%dh", d/time.Hour)
	case d%time.Minute == 0:
		return fmt.Sprintf("%dm", d/time.Minute)
	default:
		return fmt.Sprintf("%ds", d/time.Second)
	}
}

func emitGenrule(w *bytes.Buffer, t ir.Target) error {
	v := genruleView{
		Name:       t.Name,
		Srcs:       sortedCopy(t.Srcs),
		Outs:       sortedCopy(t.GenruleOuts),
		CmdLiteral: fmt.Sprintf("%q", t.GenruleCmd),
		Tags:       sortedCopy(t.Tags),
		Visibility: append([]string(nil), t.Visibility...),
	}
	return genruleTmpl.Execute(w, v)
}

func sortedCopy(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	out := append([]string(nil), in...)
	sort.Strings(out)
	return out
}

// strDict renders a Go map[string]string as a Starlark dict literal,
// keys sorted for byte-stable output. Empty maps render as "{}".
func strDict(m map[string]string) string {
	if len(m) == 0 {
		return "{}"
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var single bytes.Buffer
	single.WriteByte('{')
	for i, k := range keys {
		if i > 0 {
			single.WriteString(", ")
		}
		fmt.Fprintf(&single, "%q: %q", k, m[k])
	}
	single.WriteByte('}')
	if single.Len() <= 60 {
		return single.String()
	}
	var multi bytes.Buffer
	multi.WriteString("{\n")
	for _, k := range keys {
		fmt.Fprintf(&multi, "        %q: %q,\n", k, m[k])
	}
	multi.WriteString("    }")
	return multi.String()
}

// strList renders a Go []string as a Starlark list literal:
//
//	["a", "b"]                       (single-line if total <= 60 chars)
//	[
//	    "a",
//	    "b",
//	]                                 (multi-line otherwise)
func strList(items []string) string {
	if len(items) == 0 {
		return "[]"
	}
	// single-line trial
	var single bytes.Buffer
	single.WriteByte('[')
	for i, s := range items {
		if i > 0 {
			single.WriteString(", ")
		}
		single.WriteByte('"')
		single.WriteString(s)
		single.WriteByte('"')
	}
	single.WriteByte(']')
	if single.Len() <= 60 {
		return single.String()
	}
	// multi-line
	var multi bytes.Buffer
	multi.WriteString("[\n")
	for _, s := range items {
		fmt.Fprintf(&multi, "        %q,\n", s)
	}
	multi.WriteString("    ]")
	return multi.String()
}
