// Package bazeltoolchain renders a toolchain.Model to Bazel rules:
//
//   - BUILD.bazel: cc_toolchain + cc_toolchain_config + platform +
//     toolchain rules.
//   - cc_toolchain_config.bzl: thin wrapper around bazel_tools'
//     unix_cc_toolchain_config that fills in flags / tool paths /
//     builtin includes from the model.
//
// The output is a complete, drop-in repo subdirectory: a downstream
// `bazel build --extra_toolchains=//path:linux_x86_64_cc_toolchain
// //:smoke` resolves the right cc_toolchain for compilation.
//
// Pure rendering: takes a Model + Config (output knobs like names),
// returns bytes. Real-cmake invocation lives in toolchain.Probe.
package bazeltoolchain

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/sstriker/cmake-to-bazel/converter/internal/toolchain"
)

// Config knobs the operator passes per emission. None are required;
// sensible defaults derived from the model are applied when unset.
type Config struct {
	// PackageName is the Bazel package the emitted rules live in.
	// Defaults to "toolchain". The toolchain identifier embeds it so
	// two emissions in the same workspace don't collide.
	PackageName string

	// TargetLibc names the libc on the target. Bazel's typical
	// values: "glibc", "musl", "macosx", "msvcrt". When empty we
	// fall back to "glibc" for Linux, "macosx" for Darwin, "" for
	// other OSes.
	TargetLibc string

	// ToolchainIdentifier is the cc_toolchain_config's
	// `toolchain_identifier`. Defaults to
	// "<target_os>_<target_cpu>_<compiler_id>" lowercased.
	ToolchainIdentifier string
}

// Bundle is the result of Emit: a map from filename (relative to the
// emitted package's directory) to file content. The caller writes
// each entry to disk.
type Bundle struct {
	Files map[string][]byte
}

// Emit renders one Model + Config to a Bundle ready to write into a
// Bazel package directory. Returns an error if the model lacks a
// minimum set of fields (no languages, no compiler path).
//
// For variant-aware emission (per-build-type compile/link flag sets
// drawn from a probe matrix), use EmitResolved with a
// toolchain.ResolvedToolchain — that path populates dbg_compile_flags
// / opt_compile_flags and the matching link-flag slots.
func Emit(m *toolchain.Model, cfg Config) (*Bundle, error) {
	if m == nil {
		return nil, fmt.Errorf("bazeltoolchain.Emit: nil model")
	}
	if len(m.Languages) == 0 {
		return nil, fmt.Errorf("bazeltoolchain.Emit: model has no languages")
	}
	return emit(m, nil, cfg)
}

// EmitResolved is the variant-aware entrypoint: rt.Base provides the
// always-on flag set, rt.PerBuildType provides per-build-type
// deltas. Bazel's compilation_mode toggles (dbg, opt) map from
// CMake build types via toolchain.CompilationMode.
func EmitResolved(rt *toolchain.ResolvedToolchain, cfg Config) (*Bundle, error) {
	if rt == nil || rt.Base == nil {
		return nil, fmt.Errorf("bazeltoolchain.EmitResolved: nil ResolvedToolchain")
	}
	if len(rt.Base.Languages) == 0 {
		return nil, fmt.Errorf("bazeltoolchain.EmitResolved: base model has no languages")
	}
	return emit(rt.Base, rt, cfg)
}

func emit(m *toolchain.Model, rt *toolchain.ResolvedToolchain, cfg Config) (*Bundle, error) {
	cfg = cfg.withDefaults(m)

	build, err := emitBuildBazel(m, cfg)
	if err != nil {
		return nil, err
	}
	cfgBzl, err := emitConfigBzl(m, rt, cfg)
	if err != nil {
		return nil, err
	}
	return &Bundle{Files: map[string][]byte{
		"BUILD.bazel":             build,
		"cc_toolchain_config.bzl": cfgBzl,
	}}, nil
}

func (c Config) withDefaults(m *toolchain.Model) Config {
	if c.PackageName == "" {
		c.PackageName = "toolchain"
	}
	if c.ToolchainIdentifier == "" {
		c.ToolchainIdentifier = sanitizeID(strings.ToLower(
			fmt.Sprintf("%s_%s_%s",
				orDefault(m.TargetPlatform.OS, "unknown"),
				orDefault(m.TargetPlatform.CPU, "unknown"),
				lowestCompilerID(m),
			)))
	}
	if c.TargetLibc == "" {
		switch strings.ToLower(m.TargetPlatform.OS) {
		case "linux":
			c.TargetLibc = "glibc"
		case "darwin":
			c.TargetLibc = "macosx"
		}
	}
	return c
}

// emitBuildBazel renders the cc_toolchain + platform + toolchain
// rules. Handwritten string concatenation rather than text/template
// keeps the output stable and the rendering logic auditable.
func emitBuildBazel(m *toolchain.Model, cfg Config) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("# Generated by derive-toolchain. DO NOT EDIT.\n")
	buf.WriteString("\n")
	buf.WriteString("load(\":cc_toolchain_config.bzl\", \"cc_toolchain_config\")\n")
	buf.WriteString("\n")

	id := cfg.ToolchainIdentifier
	cpu := orDefault(m.TargetPlatform.CPU, "unknown")
	osName := strings.ToLower(orDefault(m.TargetPlatform.OS, "unknown"))

	// platform()
	fmt.Fprintf(&buf, "platform(\n    name = %q,\n    constraint_values = [\n", id+"_platform")
	if osName != "unknown" {
		fmt.Fprintf(&buf, "        %q,\n", "@platforms//os:"+osName)
	}
	if cpu != "unknown" {
		fmt.Fprintf(&buf, "        %q,\n", "@platforms//cpu:"+normalizeBazelCPU(cpu))
	}
	buf.WriteString("    ],\n)\n\n")

	// cc_toolchain_config()
	fmt.Fprintf(&buf, "cc_toolchain_config(\n    name = %q,\n)\n\n", id+"_config")

	// cc_toolchain()
	fmt.Fprintf(&buf, "cc_toolchain(\n")
	fmt.Fprintf(&buf, "    name = %q,\n", id+"_cc")
	fmt.Fprintf(&buf, "    toolchain_config = %q,\n", ":"+id+"_config")
	fmt.Fprintf(&buf, "    all_files = %q,\n", ":empty")
	fmt.Fprintf(&buf, "    compiler_files = %q,\n", ":empty")
	fmt.Fprintf(&buf, "    dwp_files = %q,\n", ":empty")
	fmt.Fprintf(&buf, "    linker_files = %q,\n", ":empty")
	fmt.Fprintf(&buf, "    objcopy_files = %q,\n", ":empty")
	fmt.Fprintf(&buf, "    strip_files = %q,\n", ":empty")
	fmt.Fprintf(&buf, "    supports_param_files = 1,\n")
	buf.WriteString(")\n\n")

	// toolchain() registration
	fmt.Fprintf(&buf, "toolchain(\n")
	fmt.Fprintf(&buf, "    name = %q,\n", id+"_toolchain")
	fmt.Fprintf(&buf, "    target_compatible_with = [\n")
	if osName != "unknown" {
		fmt.Fprintf(&buf, "        %q,\n", "@platforms//os:"+osName)
	}
	if cpu != "unknown" {
		fmt.Fprintf(&buf, "        %q,\n", "@platforms//cpu:"+normalizeBazelCPU(cpu))
	}
	buf.WriteString("    ],\n")
	fmt.Fprintf(&buf, "    toolchain = %q,\n", ":"+id+"_cc")
	fmt.Fprintf(&buf, "    toolchain_type = %q,\n", "@bazel_tools//tools/cpp:toolchain_type")
	buf.WriteString(")\n\n")

	// filegroup for cc_toolchain's *_files attrs.
	buf.WriteString("filegroup(name = \"empty\", srcs = [])\n")
	return buf.Bytes(), nil
}

// emitConfigBzl renders cc_toolchain_config.bzl: a thin wrapper
// around bazel_tools' unix_cc_toolchain_config. The wrapper passes
// the model's flags / tool paths / builtin includes into the
// upstream rule; consumers don't need to touch any of this.
//
// When rt is non-nil, per-build-type flag deltas land in
// dbg_compile_flags / opt_compile_flags (keyed by
// toolchain.CompilationMode). When rt is nil, those slots stay
// empty — the always-on `compile_flags` slot still gets the base
// CMAKE_<LANG>_FLAGS contribution either way.
func emitConfigBzl(m *toolchain.Model, rt *toolchain.ResolvedToolchain, cfg Config) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("# Generated by derive-toolchain. DO NOT EDIT.\n")
	buf.WriteString("\n")
	buf.WriteString(`load("@bazel_tools//tools/cpp:unix_cc_toolchain_config.bzl", _impl = "cc_toolchain_config")` + "\n")
	buf.WriteString("\n")

	cMost := primaryLanguage(m)
	cxx := m.Languages["CXX"]

	tools := mergedTools(m)

	osName := strings.ToLower(orDefault(m.TargetPlatform.OS, "unknown"))
	cpu := normalizeBazelCPU(orDefault(m.TargetPlatform.CPU, "unknown"))
	targetSystemName := orDefault(cMost.Target, fmt.Sprintf("%s-%s", cpu, osName))

	buf.WriteString("def cc_toolchain_config(name):\n")
	buf.WriteString("    _impl(\n")
	fmt.Fprintf(&buf, "        name = name,\n")
	fmt.Fprintf(&buf, "        cpu = %q,\n", cpu)
	fmt.Fprintf(&buf, "        compiler = %q,\n", strings.ToLower(orDefault(cMost.CompilerID, "unknown")))
	fmt.Fprintf(&buf, "        toolchain_identifier = %q,\n", cfg.ToolchainIdentifier)
	fmt.Fprintf(&buf, "        host_system_name = %q,\n", targetSystemName)
	fmt.Fprintf(&buf, "        target_system_name = %q,\n", targetSystemName)
	fmt.Fprintf(&buf, "        target_libc = %q,\n", orDefault(cfg.TargetLibc, "unknown"))
	fmt.Fprintf(&buf, "        abi_version = %q,\n", "local")
	fmt.Fprintf(&buf, "        abi_libc_version = %q,\n", "local")

	// cxx_builtin_include_directories: union across languages.
	includes := unionStrings(cMost.BuiltinIncludeDirs, cxx.BuiltinIncludeDirs)
	emitStringList(&buf, "cxx_builtin_include_directories", includes, "        ")

	// tool_paths
	emitStringMap(&buf, "tool_paths", tools, "        ")

	// compile_flags / cxx_flags / link_flags: always-on, drawn from
	// the baseline (Model.Languages[..].BaseFlags / LinkFlags).
	emitStringList(&buf, "compile_flags", cMost.BaseFlags, "        ")
	emitStringList(&buf, "cxx_flags", cxx.BaseFlags, "        ")
	emitStringList(&buf, "link_flags", cMost.LinkFlags, "        ")
	emitStringList(&buf, "link_libs", []string{}, "        ")

	// Per-mode flag sets drawn from the variant matrix when
	// available; empty otherwise.
	dbgCompile, dbgLink := variantFlagsFor(rt, "dbg")
	optCompile, optLink := variantFlagsFor(rt, "opt")
	emitStringList(&buf, "opt_compile_flags", optCompile, "        ")
	emitStringList(&buf, "opt_link_flags", optLink, "        ")
	emitStringList(&buf, "dbg_compile_flags", dbgCompile, "        ")
	emitStringList(&buf, "coverage_compile_flags", []string{}, "        ")
	emitStringList(&buf, "coverage_link_flags", []string{}, "        ")
	emitStringList(&buf, "unfiltered_compile_flags", []string{}, "        ")
	_ = dbgLink // bazel's unix_cc_toolchain_config has no dbg_link_flags slot
	buf.WriteString("    )\n")

	return buf.Bytes(), nil
}

// variantFlagsFor walks the ResolvedToolchain's per-build-type map
// looking for entries that fold to the requested compilation mode
// ("dbg" / "opt"). Returns the merged compile + link flag slices.
//
// Multiple CMake build types map to the same Bazel mode (e.g.
// Release / RelWithDebInfo / MinSizeRel all become "opt"); we
// merge dedup-preserving-order rather than picking one. Operators
// who need finer control post-process the .bzl.
func variantFlagsFor(rt *toolchain.ResolvedToolchain, mode string) (compile []string, link []string) {
	if rt == nil {
		return nil, nil
	}
	for buildType, delta := range rt.PerBuildType {
		if toolchain.CompilationMode(buildType) != mode {
			continue
		}
		// LanguageFlags["C"] is the canonical shared set; CXX
		// duplicates most of it. Use C if present, fall back to
		// CXX, then any.
		if c, ok := delta.LanguageFlags["C"]; ok {
			compile = mergeOrdered(compile, c)
		} else if cxx, ok := delta.LanguageFlags["CXX"]; ok {
			compile = mergeOrdered(compile, cxx)
		} else {
			for _, fl := range delta.LanguageFlags {
				compile = mergeOrdered(compile, fl)
				break
			}
		}
		link = mergeOrdered(link, delta.LinkFlags)
	}
	return compile, link
}

// mergeOrdered appends src to dst, deduping while preserving order.
func mergeOrdered(dst, src []string) []string {
	seen := make(map[string]bool, len(dst))
	for _, x := range dst {
		seen[x] = true
	}
	for _, x := range src {
		if !seen[x] {
			seen[x] = true
			dst = append(dst, x)
		}
	}
	return dst
}

// helpers

func emitStringList(buf *bytes.Buffer, name string, items []string, indent string) {
	if len(items) == 0 {
		fmt.Fprintf(buf, "%s%s = [],\n", indent, name)
		return
	}
	fmt.Fprintf(buf, "%s%s = [\n", indent, name)
	for _, it := range items {
		fmt.Fprintf(buf, "%s    %q,\n", indent, it)
	}
	fmt.Fprintf(buf, "%s],\n", indent)
}

func emitStringMap(buf *bytes.Buffer, name string, m map[string]string, indent string) {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	fmt.Fprintf(buf, "%s%s = {\n", indent, name)
	for _, k := range keys {
		fmt.Fprintf(buf, "%s    %q: %q,\n", indent, k, m[k])
	}
	fmt.Fprintf(buf, "%s},\n", indent)
}

// primaryLanguage picks the model's "main" language for fields that
// are language-agnostic in Bazel (compiler ID, target triple). C is
// preferred over CXX since cmake reports identical compiler info for
// both when one driver (gcc / clang) handles both.
func primaryLanguage(m *toolchain.Model) toolchain.Language {
	if l, ok := m.Languages["C"]; ok {
		return l
	}
	for _, l := range m.Languages {
		return l
	}
	return toolchain.Language{}
}

// mergedTools fills in the standard Bazel tool_paths slots from the
// model's Tools struct, falling back to PATH names ("ar", "strip",
// ...) when cmake didn't set the variable. Compilers come from the
// per-language CompilerPath.
func mergedTools(m *toolchain.Model) map[string]string {
	c := primaryLanguage(m)
	cxx := m.Languages["CXX"]

	out := map[string]string{
		"ar":      orDefault(m.Tools.AR, "/usr/bin/ar"),
		"ld":      orDefault(m.Tools.Linker, "/usr/bin/ld"),
		"cpp":     orDefault(c.CompilerPath, "/usr/bin/cpp"),
		"gcc":     orDefault(c.CompilerPath, "/usr/bin/gcc"),
		"gcov":    "/usr/bin/gcov",
		"nm":      orDefault(m.Tools.NM, "/usr/bin/nm"),
		"objcopy": orDefault(m.Tools.Objcopy, "/usr/bin/objcopy"),
		"objdump": orDefault(m.Tools.Objdump, "/usr/bin/objdump"),
		"strip":   orDefault(m.Tools.Strip, "/usr/bin/strip"),
	}
	if cxx.CompilerPath != "" {
		// cc_toolchain_config doesn't have a separate g++ slot; the
		// gcc tool path is used for both. CXX flags differ at the
		// flag-set level, not the tool level.
		_ = cxx
	}
	return out
}

func unionStrings(a, b []string) []string {
	seen := map[string]bool{}
	out := []string{}
	for _, x := range a {
		if !seen[x] {
			seen[x] = true
			out = append(out, x)
		}
	}
	for _, x := range b {
		if !seen[x] {
			seen[x] = true
			out = append(out, x)
		}
	}
	return out
}

func orDefault(v, dflt string) string {
	if v == "" {
		return dflt
	}
	return v
}

func lowestCompilerID(m *toolchain.Model) string {
	if l, ok := m.Languages["C"]; ok && l.CompilerID != "" {
		return strings.ToLower(l.CompilerID)
	}
	for _, l := range m.Languages {
		if l.CompilerID != "" {
			return strings.ToLower(l.CompilerID)
		}
	}
	return "unknown"
}

func sanitizeID(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '_':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}

// normalizeBazelCPU maps cmake's CMAKE_SYSTEM_PROCESSOR values to the
// names Bazel's @platforms//cpu:* uses. Common case: cmake reports
// "x86_64" while Bazel uses "x86_64"; aarch64 -> arm64. Operators
// can override at emit time via Config.ToolchainIdentifier if a
// platform names architectures differently.
func normalizeBazelCPU(cmakeCPU string) string {
	switch strings.ToLower(cmakeCPU) {
	case "amd64", "x86_64":
		return "x86_64"
	case "aarch64", "arm64":
		return "arm64"
	case "armv7l", "armv7", "arm":
		return "arm"
	case "i386", "i486", "i586", "i686", "x86":
		return "x86_32"
	case "ppc64le", "powerpc64le":
		return "ppc"
	case "riscv64":
		return "riscv64"
	default:
		return cmakeCPU
	}
}
