package main

import (
	"fmt"
	"path/filepath"
)

func init() {
	registerHandler(flatpakImageHandler{})
	registerHandler(snapImageHandler{})
}

// flatpakImageHandler renders kind:flatpak_image as a
// placeholder install genrule. The real plugin
// (buildstream-plugins-community's flatpak_image) composes
// dep install trees + flatpak metadata into a flatpak bundle;
// v1 produces an empty placeholder so downstream consumers
// (compose stacks, top-level image lists) can reference it
// without breaking the graph.
//
// 26 of FDSDK's elements use kind:flatpak_image (2.4 % of the
// total). They live under elements/flatpak-images/ and
// elements/extensions/. Each has a config: block with
// `directory:` (image root prefix), `exclude:` (split-rule
// domains to drop, like kind:filter), and a `metadata:` block
// of flatpak-specific manifest keys.
//
// v1 caveats:
//   - The emitted tarball is empty; bazel-build-time the
//     element doesn't actually produce a flatpak.
//   - The element's build-depends are wired onto element.Deps
//     so graph ordering + source-fetch resolution stay correct.
//   - Real flatpak-builder integration lands when the FDSDK
//     end-to-end story needs the actual image artifacts.
type flatpakImageHandler struct{}

func (flatpakImageHandler) Kind() string                                 { return "flatpak_image" }
func (flatpakImageHandler) NeedsSources() bool                           { return false }
func (flatpakImageHandler) HasProjectABuild() bool                       { return true }
func (flatpakImageHandler) DefaultReadPathsPatterns() *readPathsPatterns { return nil }

func (flatpakImageHandler) RenderA(elem *element, elemPkg string) error {
	body := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:flatpak_image — FDSDK image builder. v1 emits an empty
# install tree as a placeholder; real flatpak-builder
# integration lands when the FDSDK end-to-end story needs the
# actual image artifacts.

package(default_visibility = ["//visibility:public"])

genrule(
    name = "%[1]s_install",
    srcs = [],
    outs = ["install_tree.tar"],
    cmd = """
        EMPTY="$$(mktemp -d)"
        tar -cf "$(location install_tree.tar)" -C "$$EMPTY" .
    """,
)
`, elem.Name)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), body)
}

func (flatpakImageHandler) RenderB(elem *element, elemPkg string) error {
	body := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:flatpak_image — install tree produced by project A's
# genrule (see //elements/%[1]s in project A). Placeholder until
# the flatpak-builder integration lands.
filegroup(name = "BUILD_NOT_YET_STAGED", srcs = [])
`, elem.Name)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), body)
}

// snapImageHandler renders kind:snap_image symmetrically to
// flatpak_image. 6 of FDSDK's elements use kind:snap_image
// (under elements/snap-images/). Real snap-builder integration
// is the same v2 follow-up.
type snapImageHandler struct{}

func (snapImageHandler) Kind() string                                 { return "snap_image" }
func (snapImageHandler) NeedsSources() bool                           { return false }
func (snapImageHandler) HasProjectABuild() bool                       { return true }
func (snapImageHandler) DefaultReadPathsPatterns() *readPathsPatterns { return nil }

func (snapImageHandler) RenderA(elem *element, elemPkg string) error {
	body := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:snap_image — FDSDK snap-image builder. v1 placeholder.

package(default_visibility = ["//visibility:public"])

genrule(
    name = "%[1]s_install",
    srcs = [],
    outs = ["install_tree.tar"],
    cmd = """
        EMPTY="$$(mktemp -d)"
        tar -cf "$(location install_tree.tar)" -C "$$EMPTY" .
    """,
)
`, elem.Name)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), body)
}

func (snapImageHandler) RenderB(elem *element, elemPkg string) error {
	body := `# Generated by cmd/write-a. Do not edit by hand.
# kind:snap_image — install tree produced by project A's
# genrule. v1 placeholder until snap-builder integration lands.
filegroup(name = "BUILD_NOT_YET_STAGED", srcs = [])
`
	_ = elem
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), body)
}
