package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func init() { registerHandler(cmakeHandler{}) }

// cmakeHandler renders a kind:cmake element. The project-A side is a
// genrule invoking convert-element under Bazel's action graph; the
// project-B side is a placeholder the driver script overwrites with
// project A's converted BUILD.bazel.out plus the user's full source
// tree (project B's cc_library compiles against the real source bytes).
type cmakeHandler struct{}

func (cmakeHandler) Kind() string           { return "cmake" }
func (cmakeHandler) NeedsSources() bool     { return true }
func (cmakeHandler) HasProjectABuild() bool { return true }

func (cmakeHandler) RenderA(elem *element, elemPkg string) error {
	if err := partitionSources(elem); err != nil {
		return fmt.Errorf("partition sources: %w", err)
	}

	// Real sources are staged as files in project A's source tree;
	// the glob in the per-element BUILD picks them up. Zero stubs are
	// NOT staged on disk — they're produced at action time by the
	// zero_files starlark rule and merged into $SRC_ROOT inside the
	// genrule's cmd. The rendered project-A tree only contains the
	// files the user can actually inspect; the empty stubs are an
	// action-graph detail Bazel handles.
	srcStage := filepath.Join(elemPkg, "sources")
	if err := os.RemoveAll(srcStage); err != nil {
		return err
	}
	for _, rel := range elem.RealPaths {
		if err := copyFile(filepath.Join(elem.AbsSourceDir, rel), filepath.Join(srcStage, rel)); err != nil {
			return fmt.Errorf("stage real source %s: %w", rel, err)
		}
	}
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), cmakeElementBuild(elem))
}

func (cmakeHandler) RenderB(elem *element, elemPkg string) error {
	// Stage the FULL source tree (no narrowing). Project B's
	// cc_library needs the real source bytes to compile, so this is
	// the user's tree verbatim. (writeProjectB already cleared and
	// re-created elemPkg before calling us.)
	if err := copyTree(elem.AbsSourceDir, elemPkg); err != nil {
		return fmt.Errorf("stage element sources for project B: %w", err)
	}
	// Placeholder BUILD; the driver script overwrites this after
	// project-A's bazel build produces the converter's
	// BUILD.bazel.out. Without the placeholder, Bazel would try to
	// load() rules_cc against an empty package and fail with a
	// confusing error before the stage step ran; the placeholder
	// makes the staging-not-yet-run state explicit.
	placeholder := fmt.Sprintf(`# Placeholder for cmd/write-a-rendered project B.
# The driver script overwrites this file with project A's
# bazel-bin/elements/%s/BUILD.bazel.out (the converter's output)
# after the project-A bazel build succeeds. If this file is still
# the placeholder when project B's bazel build runs, the staging
# step was skipped.
filegroup(name = "BUILD_NOT_YET_STAGED", srcs = [])
`, elem.Name)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), placeholder)
}

// partitionSources walks the element's source tree and decides which
// paths flow as real files vs zero stubs into project A.
//
//   - With no read-set feedback (HasFeedback==false), every file is
//     real. First-run / no-narrowing shape.
//   - With feedback, the real set = the feedback set, plus all
//     CMakeLists.txt files in the source tree (cmake parses the entry
//     CMakeLists before any trace event fires; auto-including them
//     keeps cmake configure correct after narrowing).
func partitionSources(elem *element) error {
	universe := []string{}
	err := filepath.Walk(elem.AbsSourceDir, func(p string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(elem.AbsSourceDir, p)
		if err != nil {
			return err
		}
		universe = append(universe, filepath.ToSlash(rel))
		return nil
	})
	if err != nil {
		return err
	}
	sort.Strings(universe)

	// Reset to handle re-renders cleanly.
	elem.RealPaths = nil
	elem.ZeroPaths = nil

	if !elem.HasFeedback {
		elem.RealPaths = universe
		return nil
	}

	real := map[string]struct{}{}
	for _, p := range elem.ReadSet {
		real[p] = struct{}{}
	}
	for _, p := range universe {
		if filepath.Base(p) == "CMakeLists.txt" {
			real[p] = struct{}{}
		}
	}
	for _, p := range universe {
		if _, ok := real[p]; ok {
			elem.RealPaths = append(elem.RealPaths, p)
		} else {
			elem.ZeroPaths = append(elem.ZeroPaths, p)
		}
	}
	return nil
}

func cmakeElementBuild(elem *element) string {
	var b strings.Builder
	fmt.Fprintf(&b, `# Generated by cmd/write-a. Do not edit by hand.

package(default_visibility = ["//visibility:public"])
`)

	// Render the zero_files load + target only when feedback narrowed
	// the source set. First-run / no-feedback elements have an empty
	// ZeroPaths and don't need the rule at all — keeps the BUILD
	// minimal in that common case.
	if len(elem.ZeroPaths) > 0 {
		fmt.Fprintf(&b, `
load("//rules:zero_files.bzl", "zero_files")

# Files cmake's directory walks see but don't read. Materialized
# at action time as zero-length stubs whose merkle is the empty
# SHA — the action input remains content-stable across edits to
# any of these paths in the user's source tree.
zero_files(
    name = "%[1]s_zero_stubs",
    paths = [
`, elem.Name)
		for _, p := range elem.ZeroPaths {
			fmt.Fprintf(&b, "        %q,\n", "sources/"+p)
		}
		fmt.Fprintf(&b, `    ],
)
`)
	}

	// Real sources flow through a glob; CMakeLists.txt is included
	// like any other entry — the cmd's shadow merge handles every
	// source uniformly via $(SRCS).
	fmt.Fprintf(&b, `
filegroup(
    name = "%[1]s_real",
    srcs = glob(["sources/**"]),
)
`, elem.Name)

	// Compose the genrule's srcs: real-files filegroup + (when
	// narrowed) the zero_stubs target. The shadow-merge cmd handles
	// both sets uniformly: each entry contains "sources/" in its
	// path; ${path##*sources/} strips down to the source-relative
	// suffix used inside cmake's source root.
	srcsList := fmt.Sprintf(`":%s_real"`, elem.Name)
	if len(elem.ZeroPaths) > 0 {
		srcsList += fmt.Sprintf(`, ":%s_zero_stubs"`, elem.Name)
	}

	fmt.Fprintf(&b, `
genrule(
    name = "%[1]s_converted",
    srcs = [%[2]s],
    outs = [
        "BUILD.bazel.out",
        "read_paths.json",
        "cmake-config-bundle.tar",
    ],
    cmd = """
        # Build a unified source-root by merging real srcs (workspace
        # paths under elements/<name>/sources/) and zero stubs (under
        # bazel-bin/.../sources/) into a fresh shadow dir. Both share
        # a "sources/" segment in their path; strip up to the last one
        # to recover the source-relative suffix.
        SHADOW="$$(mktemp -d)"
        for src in $(SRCS); do
            rel="$${src##*sources/}"
            mkdir -p "$$SHADOW/$$(dirname "$$rel")"
            cp -L "$$src" "$$SHADOW/$$rel"
        done
        BUNDLE_DIR="$$(mktemp -d)"
        $(location //tools:convert-element) \\
            --source-root="$$SHADOW" \\
            --out-build="$(location BUILD.bazel.out)" \\
            --out-bundle-dir="$$BUNDLE_DIR" \\
            --out-read-paths="$(location read_paths.json)"
        tar -cf "$(location cmake-config-bundle.tar)" -C "$$BUNDLE_DIR" .
    """,
    tools = ["//tools:convert-element"],
)

# Typed exports project B consumes. Phase 1/2 emit the converter's
# raw outputs; later phases expand cmake-config-bundle.tar into
# the typed slices (cmake_config / pkg_config / headers / libs).
filegroup(
    name = "build_bazel",
    srcs = [":%[1]s_converted"],
    output_group = "BUILD.bazel.out",
)
`, elem.Name, srcsList)
	return b.String()
}
