package main

import (
	"fmt"
	"path/filepath"
)

func init() { registerHandler(collectManifestHandler{}) }

// collectManifestHandler renders kind:collect_manifest as an
// empty-install genrule. Real manifest collection (reading dep
// trees + emitting JSON listing every artifact under
// %{install-root}) is FDSDK-specific glue from the
// buildstream-plugins-community `collect_manifest` plugin; v1
// produces a placeholder install_tree.tar so downstream consumers
// (kind:flatpak_image, etc.) can reference it without breaking
// the graph.
//
// 18 of FDSDK's elements use kind:collect_manifest (1.6 % of the
// total). All live under elements/manifests/ and
// elements/components/*-manifest.bst.
//
// v1 caveats:
//   - The emitted tarball is empty; downstream elements that
//     consume this manifest in real builds will get nothing
//     useful from it. Fine for write-a's render success; bazel-
//     build-time correctness for these elements lands when the
//     real plugin's logic is ported.
//   - The element's build-depends are still honored at the graph
//     level (loadGraph wires them onto element.Deps), so dep-
//     ordering and source-fetch lookups stay correct.
type collectManifestHandler struct{}

func (collectManifestHandler) Kind() string           { return "collect_manifest" }
func (collectManifestHandler) NeedsSources() bool     { return false }
func (collectManifestHandler) HasProjectABuild() bool { return true }

func (collectManifestHandler) RenderA(elem *element, elemPkg string) error {
	body := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:collect_manifest — FDSDK-specific manifest collector. v1
# emits an empty install tree as a placeholder; real manifest
# collection lands when an FDSDK fixture forces it (the plugin
# walks dep install trees and produces a JSON manifest under
# %%{install-root}/usr/share/manifests/).

package(default_visibility = ["//visibility:public"])

genrule(
    name = "%[1]s_install",
    srcs = [],
    outs = ["install_tree.tar"],
    cmd = """
        EMPTY="$$(mktemp -d)"
        tar -cf "$(location install_tree.tar)" -C "$$EMPTY" .
    """,
)
`, elem.Name)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), body)
}

func (collectManifestHandler) RenderB(elem *element, elemPkg string) error {
	// kind:collect_manifest's project-B side is a placeholder
	// (same shape as kind:cmake / pipeline kinds): the driver
	// script overwrites with the typed-filegroup wrapper once
	// the install tarball is staged. v1 has no typed wrapper for
	// manifest collectors yet; downstream typed consumers get
	// added when an FDSDK fixture forces it.
	body := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:collect_manifest — install tree produced by project A's
# genrule (see //elements/%[1]s in project A). Placeholder until
# the typed-filegroup wrapper lands.
filegroup(name = "BUILD_NOT_YET_STAGED", srcs = [])
`, elem.Name)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), body)
}
