package main

import (
	"fmt"
	"path/filepath"
	"strings"
)

func init() { registerHandler(filterHandler{}) }

// filterHandler renders a kind:filter element. Filter takes exactly
// one parent element's install tree and slices it by domain — e.g.
// "give me only this lib's headers" or "drop everything in the
// runtime domain". The slicing is driven by:
//
//   - The .bst's `config:` block: include / exclude / include-orphans
//     lists of domain names.
//   - The parent element's `public:` data: the actual file globs each
//     domain name maps to (e.g. domains.runtime: ["lib/**/*.so*"]).
//
// For v1, filter renders shape-equivalent to kind:stack-with-one-dep:
// a project-B filegroup whose data references the single parent's
// primary target. The include / exclude / include-orphans config is
// parsed and recorded as a comment inside the rendered BUILD (so the
// emitted file documents what the .bst requested) but not yet enforced.
// Domain enforcement reshapes into per-dep label slicing
// (`//elements/<dep>:<dep>_runtime` etc.) and lands alongside the
// typed-filegroup wrapper for pipeline-kind outputs and the
// public-data parser that reads parent domain definitions.
type filterHandler struct{}

func (filterHandler) Kind() string           { return "filter" }
func (filterHandler) NeedsSources() bool     { return false }
func (filterHandler) HasProjectABuild() bool { return false }

// filterCfg is the .bst `config:` shape kind:filter elements share.
// Pointer-to-slice for include / exclude lets the renderer
// distinguish "not set in .bst" (nil) from "explicitly empty"
// (non-nil empty slice) — same convention pipelineHandler uses.
type filterCfg struct {
	Include        *[]string `yaml:"include"`
	Exclude        *[]string `yaml:"exclude"`
	IncludeOrphans *bool     `yaml:"include-orphans"`
}

func (filterHandler) RenderA(elem *element, elemPkg string) error {
	if len(elem.Deps) != 1 {
		return fmt.Errorf("element %q (kind:filter): expected exactly 1 dep, got %d", elem.Name, len(elem.Deps))
	}
	body := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:filter — no project-A action; element output is composed in project B.
# See //elements/%s:%s in project B's tree for the filegroup that
# slices this element's parent (//elements/%s:%s).
`, elem.Name, elem.Name, elem.Deps[0].Name, elem.Deps[0].Name)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), body)
}

func (filterHandler) RenderB(elem *element, elemPkg string) error {
	if len(elem.Deps) != 1 {
		return fmt.Errorf("element %q (kind:filter): expected exactly 1 dep, got %d", elem.Name, len(elem.Deps))
	}
	dep := elem.Deps[0]

	var cfg filterCfg
	if !elem.Bst.Config.IsZero() {
		if err := elem.Bst.Config.Decode(&cfg); err != nil {
			return fmt.Errorf("element %q (kind:filter): parse config: block: %w", elem.Name, err)
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, `# Generated by cmd/write-a. Do not edit by hand.

package(default_visibility = ["//visibility:public"])

# kind:filter — single-dep filegroup. Domain-based slicing
# (config: include / exclude / include-orphans) is recorded below
# but not yet enforced; this filegroup currently passes the parent
# through unchanged. Per-dep label slicing lands alongside the
# typed-filegroup wrapper for pipeline-kind outputs.
`)
	// Document the requested filter config inside the rendered BUILD
	// so the emitted file is self-describing — even though we don't
	// act on it yet, a reader sees exactly what the .bst asked for.
	if cfg.Include != nil {
		fmt.Fprintf(&b, "# include domains: %s\n", formatDomainList(*cfg.Include))
	}
	if cfg.Exclude != nil {
		fmt.Fprintf(&b, "# exclude domains: %s\n", formatDomainList(*cfg.Exclude))
	}
	if cfg.IncludeOrphans != nil {
		fmt.Fprintf(&b, "# include-orphans: %t\n", *cfg.IncludeOrphans)
	}
	fmt.Fprintf(&b, `filegroup(
    name = %q,
    srcs = [],
    data = [%q],
)
`, elem.Name, "//elements/"+dep.Name+":"+dep.Name)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), b.String())
}

// formatDomainList renders a domain list like "[runtime, devel]" for
// the BUILD comment. Stable ordering (input order) so byte-stable
// output across runs.
func formatDomainList(domains []string) string {
	if len(domains) == 0 {
		return "[]"
	}
	return "[" + strings.Join(domains, ", ") + "]"
}
