package main

import (
	"fmt"
	"path/filepath"
	"strings"
)

// pipelineDefaults is the per-kind default phase command set. Each
// "coarse-grained install pipeline" kind (manual, make, autotools,
// pyproject, …) is a pipelineHandler instance with its own defaults;
// .bst-supplied commands override per phase.
//
// nil vs empty-list semantics: a kind that supplies a default for a
// phase but the .bst doesn't override gets the default; a .bst that
// explicitly sets `phase-commands: []` gets nothing for that phase.
// pipelineCfg uses pointer-to-slice fields to distinguish.
type pipelineDefaults struct {
	Configure []string
	Build     []string
	Install   []string
	Strip     []string
}

// pipelineHandler is the generic coarse-grained "install pipeline"
// handler implementation. Its identity (kindName) and defaults come
// from the registered instance; everything else — source staging,
// BUILD rendering, project-B placeholder — is shared.
//
// Concretely, a single source file per kind looks like:
//
//	func init() {
//	    registerHandler(pipelineHandler{
//	        kindName: "make",
//	        defaults: pipelineDefaults{
//	            Build:   []string{"make"},
//	            Install: []string{`make DESTDIR="%{install-root}" install`},
//	        },
//	    })
//	}
type pipelineHandler struct {
	kindName string
	defaults pipelineDefaults
}

func (h pipelineHandler) Kind() string           { return h.kindName }
func (h pipelineHandler) NeedsSources() bool     { return true }
func (h pipelineHandler) HasProjectABuild() bool { return true }

// pipelineCfg is the .bst `config:` block shape every pipeline-kind
// element shares. Pointer-to-slice so the renderer can distinguish
// "not set in .bst, fall back to handler defaults" (nil) from
// "explicitly cleared in .bst" (non-nil empty slice).
type pipelineCfg struct {
	ConfigureCommands *[]string `yaml:"configure-commands"`
	BuildCommands     *[]string `yaml:"build-commands"`
	InstallCommands   *[]string `yaml:"install-commands"`
	StripCommands     *[]string `yaml:"strip-commands"`
}

func (h pipelineHandler) RenderA(elem *element, elemPkg string) error {
	var cfg pipelineCfg
	// Decode the .bst's config: only when it's actually present;
	// otherwise leave cfg zero (all phases nil → use defaults).
	if !elem.Bst.Config.IsZero() {
		if err := elem.Bst.Config.Decode(&cfg); err != nil {
			return fmt.Errorf("element %q (kind:%s): parse config: block: %w", elem.Name, h.kindName, err)
		}
	}
	// Per-phase fallback: nil pointer → handler default; non-nil
	// pointer (even empty slice) → use what the .bst declared.
	configure := mergeWithDefault(cfg.ConfigureCommands, h.defaults.Configure)
	build := mergeWithDefault(cfg.BuildCommands, h.defaults.Build)
	install := mergeWithDefault(cfg.InstallCommands, h.defaults.Install)
	strip := mergeWithDefault(cfg.StripCommands, h.defaults.Strip)

	if err := stagePipelineSources(elem, elemPkg); err != nil {
		return err
	}
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"),
		renderPipelineBuild(elem, configure, build, install, strip))
}

func (h pipelineHandler) RenderB(elem *element, elemPkg string) error {
	// All pipeline kinds expose their primary output as
	// install_tree.tar in project A; project B's wrapper for
	// downstream consumers is a follow-up. For now, a placeholder
	// (same shape as kind:cmake's BUILD_NOT_YET_STAGED) marks the
	// "driver hasn't post-processed yet" state.
	body := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:%[2]s — install tree produced by project A's genrule.
# The driver script overwrites this file with the typed-filegroup
# wrapper once that lands; until then, downstream consumers fetch
# install_tree.tar from project A directly.
filegroup(name = "BUILD_NOT_YET_STAGED", srcs = [])
`, elem.Name, h.kindName)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), body)
}

// mergeWithDefault returns the user-supplied slice when non-nil,
// otherwise the default. The empty-slice case (user explicitly set
// `phase-commands: []`) is preserved as-is via the pointer check.
func mergeWithDefault(user *[]string, def []string) []string {
	if user == nil {
		return def
	}
	return *user
}

// stagePipelineSources copies the .bst's kind:local source tree into
// the project-A package so the genrule's `srcs = glob(["sources/**"])`
// picks them up. No narrowing: pipeline kinds' commands can read any
// path arbitrarily, so feedback-driven zero stubs don't apply.
func stagePipelineSources(elem *element, elemPkg string) error {
	srcStage := filepath.Join(elemPkg, "sources")
	if err := copyTree(elem.AbsSourceDir, srcStage); err != nil {
		return fmt.Errorf("stage pipeline sources for %q: %w", elem.Name, err)
	}
	return nil
}

// renderPipelineBuild renders the per-element BUILD for a coarse-
// grained pipeline kind: a glob over staged sources + a genrule
// whose cmd stages the sources into a fresh work dir, runs each
// phase's commands in order, then tars %{install-root} as the
// element's primary output (install_tree.tar).
func renderPipelineBuild(elem *element, configure, build, install, strip []string) string {
	var b strings.Builder
	fmt.Fprintf(&b, `# Generated by cmd/write-a. Do not edit by hand.

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "%[1]s_sources",
    srcs = glob(["sources/**"]),
)

genrule(
    name = "%[1]s_install",
    srcs = [":%[1]s_sources"],
    outs = ["install_tree.tar"],
    cmd = """
        # Snapshot the exec root before any cd. Bazel resolves
        # location expressions to exec-root-relative paths, and the
        # user-provided commands below cd into the staged work dir,
        # so we restore PWD before tarring the install tree.
        EXEC_ROOT="$$PWD"
        # Stage sources into a fresh work dir; honor the original
        # source-relative layout via the same shadow-merge pattern
        # the cmake handler uses (strip the leading "sources/" of
        # each $(SRCS) entry to recover the source-relative path).
        WORK="$$(mktemp -d)"
        for src in $(SRCS); do
            rel="$${src##*sources/}"
            mkdir -p "$$WORK/$$(dirname "$$rel")"
            cp -L "$$src" "$$WORK/$$rel"
        done
        cd "$$WORK"

        # BuildStream variable bindings exposed to the pipeline kinds:
        #   %%{prefix}       — install prefix inside the install root.
        #   %%{install-root} — DESTDIR-style staging dir; tarred as
        #                      the element's output below.
        # Phase 3 supports only these two; richer variable maps land
        # alongside the autotools / pyproject siblings.
        export PREFIX=/usr
        export INSTALL_ROOT="$$(mktemp -d)"
        export PATH=/usr/local/bin:/usr/bin:/bin

%[2]s
        # Tar the install tree as the element's primary output.
        cd "$$EXEC_ROOT"
        tar -cf "$(location install_tree.tar)" -C "$$INSTALL_ROOT" .
    """,
)
`, elem.Name, renderPipelineCommands(configure, build, install, strip))
	return b.String()
}

// renderPipelineCommands flattens the four phase command lists into
// the genrule's cmd, in canonical order, with %{install-root} /
// %{prefix} substituted to the genrule's exported env vars. Each
// command runs under `set -e` (the genrule cmd block is a single
// shell script); commands within a phase are separated by newlines
// so failures at any step abort the action.
func renderPipelineCommands(configure, build, install, strip []string) string {
	var lines []string
	for _, phase := range []struct {
		label    string
		commands []string
	}{
		{"configure", configure},
		{"build", build},
		{"install", install},
		{"strip", strip},
	} {
		if len(phase.commands) == 0 {
			continue
		}
		lines = append(lines, "        # === "+phase.label+" ===")
		for _, c := range phase.commands {
			lines = append(lines, "        "+substPipelineVars(c))
		}
	}
	if len(lines) == 0 {
		// No commands at all (e.g., a kind:manual element with
		// empty config:). The genrule produces an empty install
		// tree — useful only as a degenerate fixture, but a real
		// element will always declare at least install-commands
		// or pull defaults from the kind handler.
		lines = append(lines, "        # (no pipeline commands declared; install tree will be empty)")
	}
	return strings.Join(lines, "\n")
}

// substPipelineVars maps the BuildStream variable surface the
// pipeline kinds use onto shell vars the genrule's cmd exports.
// Phase 3 supports only %{prefix} and %{install-root}; richer
// substitution lands when the variable parser arrives.
func substPipelineVars(cmd string) string {
	cmd = strings.ReplaceAll(cmd, "%{install-root}", "$$INSTALL_ROOT")
	cmd = strings.ReplaceAll(cmd, "%{prefix}", "$$PREFIX")
	return cmd
}
