package main

import (
	"fmt"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

func init() { registerHandler(manualHandler{}) }

// manualHandler renders a kind:manual element. Manual elements have
// freeform per-phase shell command lists in their `config:` block —
// configure-commands, build-commands, install-commands, strip-commands
// — that the BuildStream `manual` plugin would normally invoke in
// sequence inside a sandbox. The meta-project shape lowers them to a
// single project-A genrule whose cmd is the concatenated list with
// BuildStream's variable substitution applied.
//
// Phase 3 (this PR) supports the smallest viable subset:
//
//   - The four canonical phase command lists. Any of them may be
//     empty / absent. Order is configure → build → install → strip.
//   - %{install-root} → an action-time mktemp dir; the genrule tars
//     the dir's contents as the element's primary output.
//   - %{prefix} → /usr (matches FDSDK's project.conf default; bumped
//     out to a graph-level setting in a follow-up).
//   - kind:local sources, staged into the action's working dir
//     before the commands run.
//
// Out of scope for Phase 3:
//   - Other %{<var>} substitutions (the variable map needs to come
//     from the .bst's variables: block + project.conf-derived
//     defaults; landing the parser is a separate cut).
//   - command-subdir, depends overrides, build-uid / runtime-deps,
//     the `make` and `pyproject` siblings (their handlers are layered
//     on top of this one once the variable plumbing matures).
type manualHandler struct{}

func (manualHandler) Kind() string           { return "manual" }
func (manualHandler) NeedsSources() bool     { return true }
func (manualHandler) HasProjectABuild() bool { return true }

// manualConfig is the projection of the .bst `config:` node we read.
// Phases extending kind:manual (kind:make / kind:autotools / ...)
// can extend this struct without touching the bstFile shape.
type manualConfig struct {
	ConfigureCommands []string `yaml:"configure-commands"`
	BuildCommands     []string `yaml:"build-commands"`
	InstallCommands   []string `yaml:"install-commands"`
	StripCommands     []string `yaml:"strip-commands"`
}

func (manualHandler) RenderA(elem *element, elemPkg string) error {
	var cfg manualConfig
	if err := elem.Bst.Config.Decode(&cfg); err != nil {
		return fmt.Errorf("element %q: parse config: block: %w", elem.Name, err)
	}
	if err := stageManualSources(elem, elemPkg); err != nil {
		return err
	}
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), manualElementBuild(elem, &cfg))
}

func (manualHandler) RenderB(elem *element, elemPkg string) error {
	// Project B's shape for kind:manual is a thin filegroup wrapping
	// project A's install-tree tarball. Downstream consumers (filter,
	// stack, future cc_import-shaped wrappers) reference this label;
	// for Phase 3's acceptance the smoke driver just extracts the
	// tarball and asserts its contents.
	body := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:manual — install tree produced by project A's genrule.
# The driver script overwrites this file with the Phase-3 wrapper
# (a filegroup re-exporting the tarball under //elements/%[1]s:install).
filegroup(name = "BUILD_NOT_YET_STAGED", srcs = [])
`, elem.Name)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), body)
}

// stageManualSources is the kind:manual analog to the cmake handler's
// source staging: copy the .bst's kind:local source tree into the
// project-A package so the genrule's `srcs = glob(["sources/**"])`
// picks them up. No narrowing: kind:manual's commands can read any
// path arbitrarily, so feedback-driven zero stubs don't apply.
func stageManualSources(elem *element, elemPkg string) error {
	srcStage := filepath.Join(elemPkg, "sources")
	if err := removeAndCopyTree(elem.AbsSourceDir, srcStage); err != nil {
		return fmt.Errorf("stage manual sources for %q: %w", elem.Name, err)
	}
	return nil
}

// manualElementBuild renders the per-element BUILD for a kind:manual
// element: a glob over staged sources + a genrule whose cmd stages
// the sources into a fresh work dir, runs each phase's commands in
// order, then tars %{install-root} as the element's output.
func manualElementBuild(elem *element, cfg *manualConfig) string {
	var b strings.Builder
	fmt.Fprintf(&b, `# Generated by cmd/write-a. Do not edit by hand.

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "%[1]s_sources",
    srcs = glob(["sources/**"]),
)

genrule(
    name = "%[1]s_install",
    srcs = [":%[1]s_sources"],
    outs = ["install_tree.tar"],
    cmd = """
        # Snapshot the exec root before any cd. Bazel resolves
        # location expressions to exec-root-relative paths, and the
        # user-provided commands below cd into the staged work dir,
        # so we restore PWD before tarring the install tree.
        EXEC_ROOT="$$PWD"
        # Stage sources into a fresh work dir; honor the original
        # source-relative layout via the same shadow-merge pattern
        # the cmake handler uses (strip the leading "sources/" of
        # each $(SRCS) entry to recover the source-relative path).
        WORK="$$(mktemp -d)"
        for src in $(SRCS); do
            rel="$${src##*sources/}"
            mkdir -p "$$WORK/$$(dirname "$$rel")"
            cp -L "$$src" "$$WORK/$$rel"
        done
        cd "$$WORK"

        # BuildStream variable bindings the manual plugin exposes:
        #   %%{prefix}       — install prefix inside the install root.
        #   %%{install-root} — DESTDIR-style staging dir; tarred as
        #                      the element's output below.
        # Phase 3 supports only these two; richer variable maps land
        # with the make / autotools / pyproject siblings.
        export PREFIX=/usr
        export INSTALL_ROOT="$$(mktemp -d)"
        export PATH=/usr/local/bin:/usr/bin:/bin

%[2]s
        # Tar the install tree as the element's primary output.
        cd "$$EXEC_ROOT"
        tar -cf "$(location install_tree.tar)" -C "$$INSTALL_ROOT" .
    """,
)
`, elem.Name, renderManualCommands(cfg))
	return b.String()
}

// renderManualCommands flattens the four phase command lists into the
// genrule's cmd, in canonical order, with %{install-root} / %{prefix}
// substituted to the genrule's exported env vars. Each command runs
// under `set -e` (the genrule cmd block is a single shell script);
// commands within a phase are separated by newlines so failures at
// any step abort the action.
func renderManualCommands(cfg *manualConfig) string {
	var lines []string
	for _, phase := range []struct {
		label    string
		commands []string
	}{
		{"configure", cfg.ConfigureCommands},
		{"build", cfg.BuildCommands},
		{"install", cfg.InstallCommands},
		{"strip", cfg.StripCommands},
	} {
		if len(phase.commands) == 0 {
			continue
		}
		lines = append(lines, "        # === "+phase.label+" ===")
		for _, c := range phase.commands {
			lines = append(lines, "        "+substManualVars(c))
		}
	}
	if len(lines) == 0 {
		// No commands at all — produce an empty install tree.
		// Useful only as a degenerate test fixture.
		lines = append(lines, "        # (no manual commands declared; install tree will be empty)")
	}
	return strings.Join(lines, "\n")
}

// substManualVars maps the BuildStream variable surface kind:manual
// uses in this PR onto shell vars the genrule's cmd exports.
// Phase 3 supports only %{prefix} and %{install-root}; richer
// substitution lands when the variable parser arrives.
func substManualVars(cmd string) string {
	cmd = strings.ReplaceAll(cmd, "%{install-root}", "$$INSTALL_ROOT")
	cmd = strings.ReplaceAll(cmd, "%{prefix}", "$$PREFIX")
	return cmd
}

// removeAndCopyTree clears dst and recursively copies src into it.
// Used by handlers that need fresh per-render staging.
func removeAndCopyTree(src, dst string) error {
	// Reuse the writer's existing copyTree; the per-handler call
	// path doesn't need a separate clear step because writeProjectA
	// passes a freshly-mkdir'd elemPkg.
	if err := copyTree(src, dst); err != nil {
		return err
	}
	return nil
}

// silence "unused yaml" lints when handler_manual.go is the only
// consumer of yaml.Node decoding outside main.go.
var _ = yaml.Marshal
