package main

import (
	"fmt"
	"path/filepath"
	"strings"
)

func init() { registerHandler(stackHandler{}) }

// stackHandler renders a kind:stack element. Stack elements have no
// build; their entire output is "the union of my dependencies'
// outputs". The plan calls them "trivial" and they are: no genrule,
// no source tree, just a filegroup composing deps' labels.
//
// Project A side: stack contributes nothing actionable. Bazel's action
// graph for project A doesn't have a node for kind:stack — the element's
// project-A package is left empty (just a marker BUILD.bazel so the
// directory isn't a load error if anything ever queries it).
//
// Project B side: a filegroup whose data references each dep's primary
// target inside project B (//elements/<dep>:<dep> for kind:cmake deps,
// which after the driver's stage step is a cc_library, or a sibling
// filegroup for kind:stack-of-stacks). Downstream consumers reference
// the stack's filegroup directly.
//
// Convention assumed by the dep-label rendering: kind:cmake elements'
// converted BUILD declares a cc_library named the same as the .bst
// element (lib-a.bst → add_library(lib-a) → cc_library(name="lib-a")).
// Real FDSDK elements often diverge from this; when those phases
// land, this handler will read the converted target name from
// project A's BUILD.bazel.out (or the writer will gain a per-kind
// "primary target name" lookup) instead of assuming.
type stackHandler struct{}

func (stackHandler) Kind() string           { return "stack" }
func (stackHandler) NeedsSources() bool     { return false }
func (stackHandler) HasProjectABuild() bool { return false }

func (stackHandler) RenderA(elem *element, elemPkg string) error {
	// Stack elements have no project-A action. Drop a stub BUILD so
	// the package exists (some tooling expects every elements/<name>/
	// to be a Bazel package) but it declares no targets.
	body := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:stack — no project-A action; element output is composed in project B.
# See //elements/%s:%s in project B's tree for the filegroup that
# bundles this element's dependencies.
`, elem.Name, elem.Name)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), body)
}

func (stackHandler) RenderB(elem *element, elemPkg string) error {
	var b strings.Builder
	fmt.Fprintf(&b, `# Generated by cmd/write-a. Do not edit by hand.

package(default_visibility = ["//visibility:public"])

# kind:stack — bundle of dependencies' primary targets. The filegroup
# below has no compile-time semantics on its own; downstream
# consumers (cc_binary, another stack, a filter, …) reference it to
# pull in the union of dep outputs in one label.
filegroup(
    name = "%[1]s",
    srcs = [],
    data = [
`, elem.Name)
	// Render dep references in deterministic order.
	for _, dep := range elem.Deps {
		fmt.Fprintf(&b, "        %q,\n", "//elements/"+dep.Name+":"+dep.Name)
	}
	fmt.Fprintf(&b, `    ],
)
`)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), b.String())
}
