package main

import (
	"fmt"
	"path/filepath"
	"strings"
)

func init() { registerHandler(composeHandler{}) }

// composeHandler renders a kind:compose element. Compose is — in
// rendering shape — byte-identical to kind:stack: no project-A
// action, project B is a filegroup composing the dependencies'
// primary targets. The semantic distinction in BuildStream is that
// compose detects file-level conflicts across overlapping deps and
// fails the action; we punt that to Bazel's own conflict reporting
// (overlapping filegroups surface as collisions when consumers
// build against them).
//
// The actual BuildStream surface compose adds beyond stack —
// `integrate: true/false`, `include-orphans`, per-dep tag filters —
// is parseable but not yet enforced. Those reshape into per-dep
// label slicing (e.g. `//elements/<dep>:<dep>_runtime` vs
// `:_devel`), which lands once the typed-filegroup wrapper for
// pipeline-kind outputs lands. Until then, compose's rendering
// matches stack and the .bst's `config:` is recorded but inert.
type composeHandler struct{}

func (composeHandler) Kind() string           { return "compose" }
func (composeHandler) NeedsSources() bool     { return false }
func (composeHandler) HasProjectABuild() bool { return false }

func (composeHandler) RenderA(elem *element, elemPkg string) error {
	body := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:compose — no project-A action; element output is composed in project B.
# See //elements/%s:%s in project B's tree for the filegroup that
# bundles this element's dependencies.
`, elem.Name, elem.Name)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), body)
}

func (composeHandler) RenderB(elem *element, elemPkg string) error {
	var b strings.Builder
	fmt.Fprintf(&b, `# Generated by cmd/write-a. Do not edit by hand.

package(default_visibility = ["//visibility:public"])

# kind:compose — bundle of dependencies' primary targets with
# (eventual) cross-dep conflict detection. For now identical in
# shape to kind:stack: a filegroup composing dep labels. The
# .bst's compose-specific config (integrate / include-orphans /
# per-dep tag filters) is parsed but not yet enforced; that lands
# alongside the typed-filegroup wrapper for pipeline-kind outputs.
filegroup(
    name = "%[1]s",
    srcs = [],
    data = [
`, elem.Name)
	for _, dep := range elem.Deps {
		fmt.Fprintf(&b, "        %q,\n", "//elements/"+dep.Name+":"+dep.Name)
	}
	fmt.Fprintf(&b, `    ],
)
`)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), b.String())
}
