package main

import (
	"fmt"
	"path/filepath"
)

func init() { registerHandler(importHandler{}) }

// importHandler renders a kind:import element. Import takes a
// pre-existing source tree (kind:local for now; tarball / remote
// asset support lands when source-kind dispatch arrives) and
// exposes it as a filegroup downstream consumers can reference.
// No build action runs in either project.
//
// Project A side: a no-target marker package — same shape as
// kind:stack / kind:compose / kind:filter — because import has no
// translator action to schedule.
//
// Project B side: the source tree is copied verbatim into
// elements/<name>/, and the BUILD.bazel is a `filegroup` over
// `glob(["**/*"])` exposing every staged file. Downstream
// consumers (a kind:compose bundling imports + cmake elements,
// for example) reference `//elements/<name>:<name>` and pick up
// the staged tree.
//
// `config:` keys BuildStream's import plugin supports (`source`,
// `target`) reshape into per-element subdirectory selection — not
// yet plumbed; for v1 the entire source tree is exposed verbatim.
type importHandler struct{}

func (importHandler) Kind() string           { return "import" }
func (importHandler) NeedsSources() bool     { return true }
func (importHandler) HasProjectABuild() bool { return false }

func (importHandler) RenderA(elem *element, elemPkg string) error {
	body := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.
# kind:import — no project-A action; element output is its source
# tree, exposed as a filegroup in project B.
# See //elements/%s:%s in project B's tree for the filegroup.
`, elem.Name, elem.Name)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), body)
}

func (importHandler) RenderB(elem *element, elemPkg string) error {
	if err := stageAllSources(elem, elemPkg); err != nil {
		return err
	}
	// glob(["**/*"]) catches every staged file. The exclude on
	// BUILD.bazel keeps the filegroup self-referential-clean — the
	// rendered BUILD itself isn't part of the import's payload.
	body := fmt.Sprintf(`# Generated by cmd/write-a. Do not edit by hand.

package(default_visibility = ["//visibility:public"])

# kind:import — staged source tree exposed as a filegroup.
# Downstream consumers reference //elements/%[1]s:%[1]s to pick up
# every imported file.
filegroup(
    name = %[1]q,
    srcs = glob(["**/*"], exclude = ["BUILD.bazel"]),
)
`, elem.Name)
	return writeFile(filepath.Join(elemPkg, "BUILD.bazel"), body)
}
