package main

// Renderer for project A's //options/BUILD.bazel — one Bazel
// `string_flag` per project.conf options: entry, plus the load()
// preamble.
//
// User-configurable build settings get the Bazel-native treatment
// per docs/sources-design.md: each project.conf option becomes a
// `string_flag(name = ..., build_setting_default = ..., values =
// [...])` declared under //options. Element-level (?): branches
// keyed on these variables (handled by the next stack-on PR)
// reference the flag via per-(option, value) `config_setting`
// labels and Bazel's `select()`.
//
// target_arch is intentionally excluded: it has a Bazel-native
// home in @platforms//cpu:*, and the pipeline handler's existing
// select() lowering already targets that namespace. Including
// target_arch as a //options:string_flag would create two
// dispatch surfaces for the same identity.
//
// Boolean options ship with a closed values list of "True" /
// "False" so Bazel's string_flag enforces it; flags-typed options
// get their declared comma-separable values. Both shapes are
// rare in FDSDK relative to enum / arch.

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// optionsExcludedFromFlagRender lists option names that don't
// surface as Bazel string_flag: they have a more-native home
// (target_arch → @platforms//cpu:*).
var optionsExcludedFromFlagRender = map[string]bool{
	"target_arch": true,
}

// optionTypedSet returns the set of option-name keys declared in
// the project.conf options: block. Used by the conditional-folder
// to keep option-typed (?): branches out of the static-fold pass
// (they need to flow to the pipeline handler's select() lowering).
func optionTypedSet(options map[string]bstOption) map[string]bool {
	if len(options) == 0 {
		return nil
	}
	out := map[string]bool{}
	for name := range options {
		out[name] = true
	}
	return out
}

// writeOptionsPackage renders //options/BUILD.bazel into outDir.
// Returns nil + writes nothing when no options are declared (the
// project doesn't ship a BUILD.bazel under //options in that
// case; downstream selects() reference @platforms//cpu:* only).
func writeOptionsPackage(outDir string, options map[string]bstOption) error {
	if len(options) == 0 {
		return nil
	}
	pkgDir := filepath.Join(outDir, "options")
	if err := writeFile(filepath.Join(pkgDir, "BUILD.bazel"), renderOptionsBuild(options)); err != nil {
		return err
	}
	return nil
}

// renderOptionsBuild returns the BUILD.bazel content for the
// //options package: a load() of bazel_skylib's string_flag plus
// one rule per non-excluded option.
func renderOptionsBuild(options map[string]bstOption) string {
	names := make([]string, 0, len(options))
	for name := range options {
		if optionsExcludedFromFlagRender[name] {
			continue
		}
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	fmt.Fprintf(&b, `# Generated by cmd/write-a. Do not edit by hand.
#
# User-configurable build settings declared in the meta-project's
# project.conf options: block. Each option produces a Bazel
# string_flag here; (?): branches keyed on these variables in
# element BUILDs reference per-(option, value) config_settings
# (also in this package, generated alongside) via select().
#
# target_arch isn't exposed as a string_flag — it lives in
# @platforms//cpu:* and the pipeline handler's existing select()
# lowering targets that namespace.
load("@bazel_skylib//rules:common_settings.bzl", "string_flag")

package(default_visibility = ["//visibility:public"])
`)

	for _, name := range names {
		opt := options[name]
		fmt.Fprintln(&b)
		fmt.Fprintf(&b, "string_flag(\n")
		fmt.Fprintf(&b, "    name = %q,\n", name)
		def, values := optionDefaultAndValues(opt)
		fmt.Fprintf(&b, "    build_setting_default = %q,\n", def)
		if len(values) > 0 {
			fmt.Fprintf(&b, "    values = [\n")
			for _, v := range values {
				fmt.Fprintf(&b, "        %q,\n", v)
			}
			fmt.Fprintf(&b, "    ],\n")
		}
		fmt.Fprintf(&b, ")\n")
	}
	return b.String()
}

// optionDefaultAndValues returns the build_setting_default and
// (non-empty) values list for a string_flag declaration. It
// normalizes BuildStream's per-type quirks:
//
//   - bool: values = ["True", "False"]; default scalar matches.
//   - flags: declared values; default is a list — joined with ",".
//   - enum / arch / element / element-list: declared values + scalar default.
//
// Missing default falls through to the empty string so the flag
// declares no specific default — Bazel chooses the first value
// or rejects without an explicit setting.
func optionDefaultAndValues(opt bstOption) (string, []string) {
	values := opt.Values
	if opt.Type == "bool" && len(values) == 0 {
		values = []string{"True", "False"}
	}
	def := defaultAsString(opt.Default)
	return def, values
}

// defaultAsString reduces a yaml.Node default value to the
// canonical string a string_flag's build_setting_default takes.
// Scalars pass through verbatim. Sequences (flags-type defaults)
// join with "," — matching Bazel's typical comma-separable
// flag-list shape. Nil / zero nodes return the empty string.
func defaultAsString(n yaml.Node) string {
	switch n.Kind {
	case 0:
		return ""
	case yaml.ScalarNode:
		return n.Value
	case yaml.SequenceNode:
		parts := make([]string, 0, len(n.Content))
		for _, c := range n.Content {
			if c.Kind == yaml.ScalarNode {
				parts = append(parts, c.Value)
			}
		}
		return strings.Join(parts, ",")
	default:
		return ""
	}
}
