package main

// rules/sources.bzl renderer.
//
// The module extension declares one external repo per source
// identity in tools/sources.json. v1 (stub) generates an empty
// :tree filegroup for each repo so MODULE.bazel + use_repo
// resolve cleanly while the actual byte path (FUSE mount via
// cmd/cas-fuse) is still being scaffolded.

// renderSourcesBzl returns the static rules/sources.bzl content.
// No graph-derived data appears here — the extension reads
// tools/sources.json at evaluation time and resolves each
// declared repo to a ctx.symlink into cmd/cas-fuse's mount.
//
// Mount root is configured via the CAS_FUSE_MOUNT environment
// variable (passed through Bazel via --repo_env=CAS_FUSE_MOUNT=
// /var/cache/cmake-to-bazel/cas). Empty / unset env → the repo
// rule falls back to producing an empty :tree filegroup so
// `bazel query` and other no-fetch shapes don't fail; the
// emptiness surfaces at action time as "the genrule's input is
// empty," which is loud enough to debug.
func renderSourcesBzl() string {
	return `# Generated by cmd/write-a. Do not edit.

"""Module extension that declares one external repo per source
identity in the .bst graph. Each repo's ":tree" filegroup
ctx.symlinks into the cmd/cas-fuse mount point passed via the
CAS_FUSE_MOUNT environment variable, so source bytes live in
CAS but resolve as on-disk paths from Bazel's perspective.

Configuration:
  --repo_env=CAS_FUSE_MOUNT=/var/cache/cmake-to-bazel/cas
  --unix_digest_hash_attribute_name=user.bazel.cas.digest
  --digest_function=SHA256

The first points the rule at the daemon's mount; the second +
third let Bazel trust the daemon's pre-computed digests so input
files don't have to be read once just to be hashed.
"""

def _src_repo_impl(rctx):
    digest = rctx.attr.digest
    mount = rctx.os.environ.get("CAS_FUSE_MOUNT", "")
    if not mount or not digest:
        # Fallback: no mount configured or no digest computed yet.
        # An empty tree at least keeps load() resolution honest.
        rctx.file("WORKSPACE", "")
        rctx.file("BUILD.bazel", '''filegroup(
    name = "tree",
    srcs = [],
    visibility = ["//visibility:public"],
)
''')
        return
    target = mount + "/blobs/directory/" + digest
    rctx.symlink(target, "tree_dir")
    rctx.file("WORKSPACE", "")
    rctx.file("BUILD.bazel", '''# Generated by rules/sources.bzl.
#
# Two access shapes:
#   :tree                          — opaque filegroup over the
#                                    whole staged tree (used by
#                                    coarse genrules that want
#                                    "give me everything").
#   :tree_dir/<path/to/file>       — per-file label (via the
#                                    exports_files glob below).
#                                    Used by:
#                                      - project A's cmake
#                                        narrowing genrule, where
#                                        srcs explicitly enumerates
#                                        the read-paths-real subset
#                                        (zero files come from a
#                                        sibling zero_files target).
#                                      - project B's cc_library /
#                                        cc_binary, where srcs
#                                        references each compiled
#                                        source by digest-stable
#                                        Bazel label.
exports_files(
    glob(["tree_dir/**"], allow_empty = True),
)

filegroup(
    name = "tree",
    srcs = glob(["tree_dir/**"], allow_empty = True),
    visibility = ["//visibility:public"],
)
''')

_src_repo = repository_rule(
    implementation = _src_repo_impl,
    attrs = {
        "digest": attr.string(mandatory = True),
    },
    environ = ["CAS_FUSE_MOUNT"],
)

def _sources_impl(module_ctx):
    json_label = None
    for mod in module_ctx.modules:
        for tag in mod.tags.from_json:
            json_label = tag.path
    if json_label == None:
        fail("sources extension: at least one .from_json(path = ...) tag required")
    raw = module_ctx.read(json_label)
    data = json.decode(raw)
    for entry in data.get("sources", []):
        _src_repo(
            name = "src_" + entry["key"],
            digest = entry.get("digest", ""),
        )

sources = module_extension(
    implementation = _sources_impl,
    tag_classes = {
        "from_json": tag_class(attrs = {"path": attr.label(mandatory = True)}),
    },
)
`
}
