package main

// rules/sources.bzl renderer.
//
// The module extension declares one external repo per source
// identity in tools/sources.json. v1 (stub) generates an empty
// :tree filegroup for each repo so MODULE.bazel + use_repo
// resolve cleanly while the actual byte path (FUSE mount via
// cmd/cas-fuse) is still being scaffolded.

// renderSourcesBzl returns the static rules/sources.bzl content.
// No graph-derived data appears here — the extension reads
// tools/sources.json at evaluation time, so this file is the same
// across all generated workspaces.
func renderSourcesBzl() string {
	return `# Generated by cmd/write-a. Do not edit.

"""Module extension that declares one external repo per source
identity in the .bst graph. Reads tools/sources.json (also
generated by write-a) so MODULE.bazel doesn't need to enumerate
source metadata directly.

v1: stub repos with an empty :tree filegroup. Subsequent PRs
swap the stub for a ctx.symlink into cmd/cas-fuse's mount.
"""

def _src_repo_impl(rctx):
    rctx.file("WORKSPACE", "")
    rctx.file("BUILD.bazel", '''filegroup(
    name = "tree",
    srcs = [],
    visibility = ["//visibility:public"],
)
''')

_src_repo = repository_rule(
    implementation = _src_repo_impl,
    attrs = {},
)

def _sources_impl(module_ctx):
    # All callers (project A, project B) point at the same JSON.
    # We resolve it via the only tag instance.
    json_label = None
    for mod in module_ctx.modules:
        for tag in mod.tags.from_json:
            json_label = tag.path
    if json_label == None:
        fail("sources extension: at least one .from_json(path = ...) tag required")
    raw = module_ctx.read(json_label)
    data = json.decode(raw)
    for entry in data.get("sources", []):
        _src_repo(name = "src_" + entry["key"])

sources = module_extension(
    implementation = _sources_impl,
    tag_classes = {
        "from_json": tag_class(attrs = {"path": attr.label(mandatory = True)}),
    },
)
`
}
